import { describe, test, expect, mock } from 'bun:test';
import { join, dirname } from 'node:path';
import { makePRD, makeStory, makeNaxConfig, makeTestContext } from '../../../test/helpers';

const root = '/repo';
const pathProbe = (...paths: string[]) => (p: string) => paths.includes(p);
const story = (id: string, fields: Record<string, unknown> = {}) => makeStory({ id, ...fields });
const prdOf = (...stories: ReturnType<typeof makeStory>[]) => makePRD({ userStories: stories });
const validDraft = (...ids: string[]) => prdOf(...ids.map(id => story(id, { acceptanceCriteria: ['A runtime behavior is observed'], routing: { complexity: 'simple', testStrategy: 'tdd-simple', reasoning: 'Small change' } })));
const spec = (...lines: string[]) => ['## Stories', ...lines].join('\n');
const declared = spec('1. **US-001: Core** — `Workdir: packages/core` — no dependencies', '2. **US-002: API** — `Workdir: apps/api` — depends on US-001');
const five = spec(...[1,2,3,4,5].map(n => `${n}. **US-00${n}: Story ${n}** — no dependencies`));
const work = async () => import('../../../src/prd/workdir-canonical');
const structure = async () => import('../../../src/prd/spec-structure');
const builder = async () => new (await import('../../../src/prompts/builders/plan-builder')).PlanPromptBuilder();
const promptText = (parts: { taskContext: string; outputFormat: string }) => `${parts.taskContext}\n${parts.outputFormat}`;
const build = async (content: string, packages: string[] = []) => promptText((await builder()).build(content, 'context', '/out/plan.md', packages));
async function persist(input: ReturnType<typeof makePRD>, content = '', opts: Record<string, unknown> = {}) {
  const { _persistPrdDeps, finalizeAndWritePrd } = await import('../../../src/plan/strategies/persist-prd');
  const originals = { ..._persistPrdDeps };
  const written: string[] = [];
  const outputPath = '/repo/.nax/features/f/prd.json';
  try {
    _persistPrdDeps.discoverWorkspacePackages = async () => ['packages/lib'];
    _persistPrdDeps.existsSync = () => opts.draftExists === true;
    const { draftExists: _draftExists, ...overrides } = opts;
    const args = { prd: input, specContent: content, featureName: 'f', projectName: 'p', agentRouting: undefined, profileName: undefined, models: makeNaxConfig().models, defaultAgent: 'claude', outputPath, repoRoot: root, writeFile: async (_p: string, text: string) => { written.push(text); }, ...overrides };
    return { result: await finalizeAndWritePrd(args), written, outputPath };
  } finally { Object.assign(_persistPrdDeps, originals); }
}

describe('plan-prd-fidelity acceptance', () => {
  test('AC-1: existing repo-rooted path wins', async () => { const { canonicalizeDeclaredPath: f } = await work(); expect(f('docs/pipelines/report.pipeline.json','packages/lib',root,pathProbe('/repo/docs/pipelines/report.pipeline.json'))).toEqual({path:'docs/pipelines/report.pipeline.json',respelled:false}); });
  test('AC-2: absent path remains repo-rooted', async () => { const { canonicalizeDeclaredPath: f } = await work(); const r = f('docs/pipelines/report.pipeline.json','packages/lib',root,()=>false); expect(r).toEqual({path:'docs/pipelines/report.pipeline.json',respelled:false}); expect(r.path.startsWith('packages/lib/')).toBe(false); });
  test('AC-3: cross-package path remains repo-rooted', async () => { const { canonicalizeDeclaredPath: f } = await work(); expect(f('packages/db/src/schema.ts','apps/api',root,pathProbe('/repo/packages/db/src/schema.ts'))).toEqual({path:'packages/db/src/schema.ts',respelled:false}); });
  test('AC-4: existing package path is respelled', async () => { const { canonicalizeDeclaredPath: f } = await work(); expect(f('src/a.ts','packages/lib',root,pathProbe('/repo/packages/lib/src/a.ts'))).toEqual({path:'packages/lib/src/a.ts',respelled:true}); });
  test('AC-5: repo reading has precedence when both exist', async () => { const { canonicalizeDeclaredPath: f } = await work(); expect(f('src/a.ts','packages/lib',root,pathProbe('/repo/src/a.ts','/repo/packages/lib/src/a.ts'))).toEqual({path:'src/a.ts',respelled:false}); });
  test('AC-6: spelling cleanup does not count as respelling', async () => { const { canonicalizeDeclaredPath: f } = await work(); for (const exists of [()=>true,()=>false]) expect(f('./packages/lib/src/a.ts/','packages/lib',root,exists)).toEqual({path:'packages/lib/src/a.ts',respelled:false}); });
  test('AC-7: root workdir avoids filesystem probe', async () => { const { canonicalizeDeclaredPath: f } = await work(); const probe = mock(()=>true); expect(f('src/a.ts','.',root,probe)).toEqual({path:'src/a.ts',respelled:false}); expect(probe).not.toHaveBeenCalled(); });
  test('AC-8: missing expected file remains in repo frame', async () => { const { canonicalizePrdWorkdirs: f } = await work(); const r=f(prdOf(story('US-001',{workdir:'packages/lib',expectedFiles:['docs/pipelines/report.pipeline.json']})),root,['packages/lib'],()=>false); expect(r.prd.userStories[0].expectedFiles).toEqual(['docs/pipelines/report.pipeline.json']); expect(r.respelled).toEqual([]); });
  test('AC-9: repo-rooted context paths and citations survive', async () => { const { canonicalizePrdWorkdirs: f }=await work(); const files=['packages/db/src/schema.ts',{path:'docs/design.md',factId:'F-1'}]; const r=f(prdOf(story('US-001',{workdir:'apps/api',contextFiles:files})),root,['apps/api'],pathProbe('/repo/packages/db/src/schema.ts','/repo/docs/design.md')); expect(r.prd.userStories[0].contextFiles).toEqual(files); });
  test('AC-10: repo-rooted modified files remain unchanged', async () => { const {canonicalizePrdWorkdirs:f}=await work(); const files=[{path:'apps/api/tests/test_count.py',reason:'r'}]; const r=f(prdOf(story('US-001',{workdir:'packages/lib',modifiedFiles:files})),root,['packages/lib'],pathProbe('/repo/apps/api/tests/test_count.py')); expect(r.prd.userStories[0].modifiedFiles).toEqual(files); expect(r.respelled).toEqual([]); });
  test('AC-11: context file respelling is reported', async () => { const {canonicalizePrdWorkdirs:f}=await work(); const r=f(prdOf(story('US-002',{workdir:'packages/lib',contextFiles:['src/a.ts']})),root,['packages/lib'],pathProbe('/repo/packages/lib/src/a.ts')); expect(r.respelled).toEqual([{storyId:'US-002',field:'contextFiles',from:'src/a.ts',to:'packages/lib/src/a.ts'}]); expect(r.prd.userStories[0].contextFiles).toEqual(['packages/lib/src/a.ts']); });
  test('AC-12: canonicalization is idempotent', async () => { const {canonicalizePrdWorkdirs:f}=await work(); const probe=pathProbe('/repo/packages/lib/src/a.ts'); const first=f(prdOf(story('US-002',{workdir:'packages/lib',contextFiles:['src/a.ts']})),root,['packages/lib'],probe); const second=f(first.prd,root,['packages/lib'],probe); expect(second.prd.userStories).toEqual(first.prd.userStories); expect(second.respelled).toEqual([]); });
  test('AC-13: declared spelling normalizes separators', async () => { const {normalizeDeclaredPathSpelling:f}=await work(); expect(f('.\\packages\\lib\\src\\a.ts\\')).toBe('packages/lib/src/a.ts'); expect(f('packages/lib/src/a.ts')).toBe('packages/lib/src/a.ts'); });
  test('AC-14: cross-package declarations are canonical', async () => { const {findNonCanonicalDeclaredPaths:f}=await work(); expect(f(prdOf(story('US-1',{workdirSource:'stated',workdir:'packages/lib',contextFiles:['docs/x.md'],modifiedFiles:[{path:'apps/api/tests/t.py',reason:''}]})))).toEqual([]); });
  test('AC-15: spelling artifacts are reported', async () => { const {findNonCanonicalDeclaredPaths:f}=await work(); expect(f(prdOf(story('US-1',{workdirSource:'stated',workdir:'packages/lib',expectedFiles:['./packages/lib/src/new.ts']})))).toEqual([{storyId:'US-1',field:'expectedFiles',path:'./packages/lib/src/new.ts'}]); });
  test('AC-16: persistence warns once on re-spell and writes corrected path', async () => { const deps=await import('../../../src/plan/strategies/persist-prd'); const logger=(await import('../../../src/logger')).getLogger(); const old=logger.warn; const warnings: unknown[][]=[]; logger.warn=(...args: Parameters<typeof old>)=>{warnings.push(args);}; const original={...deps._persistPrdDeps}; try { deps._persistPrdDeps.discoverWorkspacePackages=async()=>['packages/lib']; deps._persistPrdDeps.existsSync=pathProbe('/repo/packages/lib/src/a.ts'); let written=''; await deps.finalizeAndWritePrd({prd:prdOf(story('US-002',{workdir:'packages/lib',contextFiles:['src/a.ts']})),specContent:'',featureName:'f',projectName:'p',agentRouting:undefined,profileName:undefined,models:makeNaxConfig().models,defaultAgent:'claude',outputPath:'/repo/prd.json',repoRoot:root,writeFile:async(_p,s)=>{written=s;}}); expect(warnings.filter(x=>x[1]==='declared paths spelled package-relative were re-spelled into the repo frame')).toHaveLength(1); expect(warnings.find(x=>x[1]==='declared paths spelled package-relative were re-spelled into the repo frame')?.[2]).toMatchObject({respelled:[{storyId:'US-002',field:'contextFiles',from:'src/a.ts',to:'packages/lib/src/a.ts'}]}); expect(JSON.parse(written).userStories[0].contextFiles).toEqual(['packages/lib/src/a.ts']); } finally { logger.warn=old; Object.assign(deps._persistPrdDeps,original); } });
  test('AC-17: persistence keeps absent path without frame warning', async () => { const logger=(await import('../../../src/logger')).getLogger(); const old=logger.warn; const messages:string[]=[]; logger.warn=(stage,message)=>{if(stage==='plan') messages.push(message);}; try { const r=await persist(prdOf(story('US-001',{workdir:'packages/lib',expectedFiles:['docs/pipelines/report.pipeline.json']}))); expect(JSON.parse(r.written[0]).userStories[0].expectedFiles).toEqual(['docs/pipelines/report.pipeline.json']); expect(messages.some(x=>x.includes('outside the repo frame'))).toBe(false); } finally {logger.warn=old;} });
  test('AC-18: stamped story scope files stay repo-rooted', async () => { const { _scopeFilesDeps,resolveScopeFiles }=await import('../../../src/pipeline/scope-files'); const old={..._scopeFilesDeps}; try { _scopeFilesDeps.resolveEffectiveRef=async()=> 'ref'; _scopeFilesDeps.collectDiffFileList=async()=>[]; expect(await resolveScopeFiles(makeTestContext({story:story('US-1',{workdirSource:'stated',workdir:'packages/lib',contextFiles:['docs/x.md']}),workdir:root,projectDir:root}))).toEqual(['docs/x.md']); } finally {Object.assign(_scopeFilesDeps,old);} });
  test('AC-19: legacy story scope files are reframed', async () => { const {_scopeFilesDeps,resolveScopeFiles}=await import('../../../src/pipeline/scope-files'); const old={..._scopeFilesDeps}; try { _scopeFilesDeps.resolveEffectiveRef=async()=> 'ref'; _scopeFilesDeps.collectDiffFileList=async()=>[]; expect(await resolveScopeFiles(makeTestContext({story:story('US-1',{workdir:'packages/app',contextFiles:['src/declared.ts']}),workdir:root,projectDir:root}))).toEqual(['packages/app/src/declared.ts']); } finally {Object.assign(_scopeFilesDeps,old);} });
  test('AC-20: scoped canonicalization leaves other stories untouched', async () => {const {canonicalizePrdWorkdirs:f}=await work(); const other=story('US-2',{workdir:'packages/lib',contextFiles:['src/a.ts']}); const r=f(prdOf(story('US-1'),other),root,['packages/lib'],pathProbe('/repo/packages/lib/src/a.ts'),{only:new Set(['US-1'])}); expect(r.prd.userStories[1]).toEqual(other); expect(r.prd.userStories[1].contextFiles).toEqual(['src/a.ts']); expect(r.respelled.filter(x=>x.storyId==='US-2')).toEqual([]); });
  test('AC-21: extract story list in document order', async () => {const {extractSpecStructure:f}=await structure(); expect(f(declared)).toEqual({stories:[{id:'US-001',workdir:'packages/core',dependsOn:[]},{id:'US-002',workdir:'apps/api',dependsOn:['US-001']}],warnings:[]}); });
  test('AC-22: Context Files lead-in has workdir', async () => {const {extractSpecStructure:f}=await structure(); expect(f('### Context Files\n**US-003**\n_Workdir `apps/web`._').stories).toContainEqual(expect.objectContaining({id:'US-003',workdir:'apps/web'})); });
  test('AC-23: parse three dependency statement variants', async () => {const {extractSpecStructure:f}=await structure(); const s=spec('**US-004: A**','- **Depends on:** US-001 (shared type)','**US-005: B**','*(depends on US-001, US-002 and US-003)*','**US-006: C**','- Depends on: none'); const r=f(s); expect(r.stories.map(x=>x.dependsOn)).toEqual([['US-001'],['US-001','US-002','US-003'],[]]); expect(r.warnings).toEqual([]); });
  test('AC-24: unstated dependencies remain undefined', async () => {const {extractSpecStructure:f}=await structure(); const r=f(spec('**US-001: A**')); expect(r.stories[0].dependsOn).toBeUndefined(); expect(r.warnings.filter(x=>x.field==='dependsOn')).toEqual([]); });
  test('AC-25: modifies prose does not supply dependencies', async () => {const {extractSpecStructure:f}=await structure(); const r=f(spec('**US-002: A**','### Modifies','**US-002**','the count test depends on US-003\'s registration')); expect(r.stories.find(x=>x.id==='US-002')?.dependsOn).toBeUndefined(); expect(r.warnings).toEqual([]); });
  test('AC-26: conflicting workdirs produce one warning', async () => {const {extractSpecStructure:f}=await structure(); const r=f(spec('**US-002: A**','Workdir: packages/lib','Workdir: apps/api')); expect(r.stories[0].workdir).toBeUndefined(); expect(r.warnings).toHaveLength(1); expect(r.warnings[0]).toMatchObject({storyId:'US-002',field:'workdir',message:expect.any(String)}); expect(r.warnings[0].message.length).toBeGreaterThan(0); });
  test('AC-27: spec with no story ids imposes no structure', async () => {const {findSpecStructureViolations:f}=await structure(); expect(f(prdOf(story('US-001'),story('US-002'),story('US-003')),'## Stories\nNo story IDs.')).toEqual([]); });
  test('AC-28: missing stories precede other violation kinds', async () => {const {findSpecStructureViolations:f}=await structure(); const r=f(prdOf(story('US-001'),story('US-002'),story('US-003'),story('US-005')),five); expect(r[0]).toEqual({kind:'missing-story',storyId:'US-004'}); const order=['missing-story','extra-story','workdir-mismatch','dependencies-mismatch','orphan-modifies']; expect(r.map(x=>order.indexOf(x.kind))).toEqual([...r.map(x=>order.indexOf(x.kind))].sort((a,b)=>a-b)); });
  test('AC-29: only US-006 is extra', async () => {const {findSpecStructureViolations:f}=await structure(); expect(f(prdOf(...[1,2,3,4,5,6].map(n=>story(`US-00${n}`))),five).filter(x=>x.kind==='extra-story')).toEqual([{kind:'extra-story',storyId:'US-006'}]); });
  test('AC-30: mismatched workdir is reported after normalization', async () => {const {findSpecStructureViolations:f}=await structure(); const s=spec('**US-004: A**','Workdir: apps/api'); expect(f(prdOf(story('US-004',{workdir:'packages/lib'})),s)).toContainEqual({kind:'workdir-mismatch',storyId:'US-004',expected:'apps/api',actual:'packages/lib'}); });
  test('AC-31: missing PRD workdir is not mismatch', async () => {const {findSpecStructureViolations:f}=await structure(); expect(f(prdOf(story('US-004')),spec('**US-004: A**','Workdir: apps/api')).filter(x=>x.kind==='workdir-mismatch'&&x.storyId==='US-004')).toEqual([]); });
  test('AC-32: dependency mismatch preserves spec order', async () => {const {findSpecStructureViolations:f}=await structure(); expect(f(prdOf(story('US-001'),story('US-003'),story('US-005',{dependencies:['US-001']})),spec('**US-001: A**','**US-003: B**','**US-005: C**','depends on US-001, US-003'))).toContainEqual({kind:'dependencies-mismatch',storyId:'US-005',expected:['US-001','US-003'],actual:['US-001']}); });
  test('AC-33: explicit none forbids dependency', async () => {const {findSpecStructureViolations:f}=await structure(); expect(f(prdOf(story('US-001'),story('US-002',{dependencies:['US-001']})),spec('**US-001: A**','**US-002: B**','no dependencies'))).toContainEqual({kind:'dependencies-mismatch',storyId:'US-002',expected:[],actual:['US-001']}); });
  test('AC-34: orphan modifies carries path', async () => {const {findSpecStructureViolations:f}=await structure(); expect(f(prdOf(story('US-001')),spec('**US-001: A**','**US-004: B**','### Modifies','**US-004**','- `apps/api/tests/test_count.py` — count test'))).toContainEqual({kind:'orphan-modifies',storyId:'US-004',path:'apps/api/tests/test_count.py'}); });
  test('AC-35: workdir backfill is immutable', async () => {const {backfillSpecWorkdirs:f}=await structure(); const input=prdOf(story('US-004')); const r=f(input,{stories:[{id:'US-004',workdir:'apps/api'}],warnings:[]}); expect(r.prd).not.toBe(input); expect(r.prd.userStories[0].workdir).toBe('apps/api'); expect(r.backfilled).toEqual(['US-004']); expect(input.userStories[0].workdir).toBeUndefined(); });
  test('AC-36: dependency formatter is exact', async () => {const {formatSpecStructureViolation:f}=await structure(); expect(f({kind:'dependencies-mismatch',storyId:'US-005',expected:['US-001','US-003'],actual:['US-001']})).toBe('US-005: dependencies are [US-001]; the spec says [US-001, US-003]'); });
  test('AC-37: unscoped violation rejects and renames existing draft', async () => {const deps=await import('../../../src/plan/strategies/persist-prd'); const original={...deps._persistPrdDeps}; const rename=mock(()=>{}); const write=mock(async()=>{}); const outputPath='/repo/prd.json'; try {deps._persistPrdDeps.existsSync=()=>true; deps._persistPrdDeps.renameSync=rename; await expect(persist(prdOf(story('US-001')),spec('**US-001: A**','**US-004: B**'),{outputPath,writeFile:write,draftExists:true})).rejects.toMatchObject({code:'PLAN_SPEC_STRUCTURE_VIOLATION',data:{stage:'plan',violations:expect.arrayContaining([{kind:'missing-story',storyId:'US-004'}])},message:expect.stringContaining('US-004: missing — the spec declares it; never merge or rename a spec story')}); expect(rename).toHaveBeenCalledTimes(1); expect(rename).toHaveBeenCalledWith(outputPath,join(dirname(outputPath),'prd.rejected.json')); expect(write).not.toHaveBeenCalled(); } finally {Object.assign(deps._persistPrdDeps,original);} });
  test('AC-38: persistence backfills spec workdir and warns', async () => {const logger=(await import('../../../src/logger')).getLogger(); const old=logger.warn; const calls:unknown[][]=[]; logger.warn=(...a:Parameters<typeof old>)=>{calls.push(a);}; try {const r=await persist(prdOf(story('US-004')),spec('**US-004: A**','Workdir: apps/api')); expect(JSON.parse(r.written[0]).userStories[0].workdir).toBe('apps/api'); expect(calls).toContainEqual(['plan','PRD stories had no workdir — filled from the spec\'s Workdir',{storyIds:['US-004']}]); } finally {logger.warn=old;} });
  test('AC-39: single strategy propagates structure violation without degraded result', async () => {const {SinglePlanStrategy,_singlePlanDeps}=await import('../../../src/plan/strategies/single'); const old=_singlePlanDeps.callOp; const deps=await import('../../../src/plan/strategies/persist-prd'); const original={...deps._persistPrdDeps}; const rename=mock(()=>{}); const write=mock(async()=>{}); try { _singlePlanDeps.callOp=async()=>prdOf(story('US-001')); deps._persistPrdDeps.existsSync=()=>true; deps._persistPrdDeps.renameSync=rename; const ctx=await planContext(spec('**US-001: A**','**US-004: B**'),write); await expect(new SinglePlanStrategy().execute(ctx)).rejects.toMatchObject({code:'PLAN_SPEC_STRUCTURE_VIOLATION'}); expect(rename).toHaveBeenCalledWith(ctx.outputPath,join(dirname(ctx.outputPath),'prd.rejected.json')); expect(write).not.toHaveBeenCalled(); } finally {_singlePlanDeps.callOp=old;Object.assign(deps._persistPrdDeps,original);} });
  test('AC-40: refine strategy rejects rather than degrading structure mismatch', async () => {const {RefinePlanStrategy,_refinePlanDeps}=await import('../../../src/plan/strategies/refine'); const old=_refinePlanDeps.callOp; try {_refinePlanDeps.callOp=async()=>prdOf(story('US-001')); await expect(new RefinePlanStrategy().execute(await planContext(spec('**US-001: A**','**US-004: B**')))).rejects.toMatchObject({code:'PLAN_SPEC_STRUCTURE_VIOLATION'}); } finally {_refinePlanDeps.callOp=old;} });
  test('AC-41: scoped write bypasses spec structure', async () => {const deps=await import('../../../src/plan/strategies/persist-prd'); const old={...deps._persistPrdDeps}; const rename=mock(()=>{}); const write=mock(async()=>{}); try {deps._persistPrdDeps.renameSync=rename; const r=await persist(prdOf(story('US-009')),spec('**US-001: A**'),{scope:new Set(['US-009']),writeFile:write}); expect(r.result).toBe(r.outputPath); expect(write).toHaveBeenCalledTimes(1); expect(rename).not.toHaveBeenCalled();} finally {Object.assign(deps._persistPrdDeps,old);} });
  test('AC-42: unknown Modifies story lint finding is stable', async () => {const {lintSpecContent}=await import('../../../src/prd/spec-lint'); const findings=lintSpecContent(spec('**US-001: A**','### Modifies','**US-009**','- `src/a.ts` — reason')); expect(findings).toEqual(expect.arrayContaining([expect.objectContaining({code:'modifies-unknown-story'})])); expect(findings.find(x=>x.code==='modifies-unknown-story')?.message).toContain('US-009'); expect(findings.filter(x=>x.code==='modifies-unknown-story').map(x=>({code:x.code,level:x.level}))).toEqual([{code:'modifies-unknown-story',level:'error'}]); });
  test('AC-43: conflicting dependency declarations are unenforced', async () => {const {extractSpecStructure,findSpecStructureViolations}=await structure(); const s=spec('**US-002: A**','depends on none','depends on US-001'); const r=extractSpecStructure(s); expect(r.stories[0].dependsOn).toBeUndefined(); expect(r.warnings).toContainEqual(expect.objectContaining({storyId:'US-002',field:'dependsOn'})); expect(findSpecStructureViolations(prdOf(story('US-002',{dependencies:['US-001']})),s).filter(x=>x.kind==='dependencies-mismatch')).toEqual([]); });
  test('AC-44: unstated dependencies are unenforced', async () => {const {findSpecStructureViolations:f}=await structure(); expect(f(prdOf(story('US-001',{dependencies:['US-001']})),spec('**US-001: A**')).filter(x=>x.kind==='dependencies-mismatch')).toEqual([]); });
  test('AC-45: absent draft is not renamed on structure violation', async () => {const deps=await import('../../../src/plan/strategies/persist-prd'); const old={...deps._persistPrdDeps}; const rename=mock(()=>{}); try {deps._persistPrdDeps.existsSync=()=>false; deps._persistPrdDeps.renameSync=rename; await expect(persist(prdOf(story('US-001')),spec('**US-001: A**','**US-004: B**'))).rejects.toMatchObject({code:'PLAN_SPEC_STRUCTURE_VIOLATION'}); expect(rename).not.toHaveBeenCalled();} finally {Object.assign(deps._persistPrdDeps,old);} });
  test('AC-46: ambiguous spec workdir logs exactly one warning and continues', async () => {const logger=(await import('../../../src/logger')).getLogger(); const old=logger.warn; const calls:unknown[][]=[]; logger.warn=(...a:Parameters<typeof old>)=>{calls.push(a);}; try {const r=await persist(prdOf(story('US-001')),spec('**US-001: A**','Workdir: packages/lib','Workdir: apps/api')); expect(r.written).toHaveLength(1); const matches=calls.filter(x=>x[1]==='spec story structure could not be read — field not enforced'); expect(matches).toHaveLength(1); expect(matches[0][2]).toMatchObject({storyId:'US-001',field:'workdir',message:expect.any(String)}); } finally {logger.warn=old;} });
  test('AC-47: binding table follows spec in prompt', async () => {const p=await build(declared); expect(p.indexOf('## Binding Story Structure')).toBeGreaterThan(p.indexOf('## Spec')); expect(p).toMatch(/\|[^\n]*US-001[^\n]*packages\/core[^\n]*none[^\n]*\|/); expect(p).toMatch(/\|[^\n]*US-002[^\n]*apps\/api[^\n]*US-001[^\n]*\|/); });
  test('AC-48: no binding section with no spec stories', async () => {expect(await build('## Overview\nNo story identifiers')).not.toContain('## Binding Story Structure'); });
  test('AC-49: unstated binding fields are marked', async () => {const p=await build(spec('**US-001: A**')); expect(p).toMatch(/\|[^\n]*US-001[^\n]*\(not stated\)[^\n]*\(not stated\)[^\n]*\|/); });
  test('AC-50: package advice respects binding workdir', async () => {const p=await build(declared,['packages/core']); expect(p).toContain('Set each story\'s "workdir" to the Workdir the Binding Story Structure lists; for a story whose Workdir is not stated, set it to the relevant package path.'); expect(p).not.toContain('For each user story, set the "workdir" field to the relevant package path…'); });
  test('AC-51: declared test-only stories are protected', async () => {const p=await build(declared); const section=p.split('## Binding Story Structure')[1].split('\n## ')[0]; expect(section).toContain('A spec story whose acceptance criteria are all integration or test criteria stays its own story: the Story Rules about combining small tasks and about test-only stories do not apply to a story the spec declares.'); });
  test('AC-52: refine dependency rules conditional on structure', async () => {const b=await builder(); const phrase='Never add or remove a dependency of a story the Binding Story Structure lists, and never merge, split or rename one of its stories.'; expect(b.buildRefineContinuation('out.md',false,true).split('#### dependency-minimization')[1].split('#### ')[0]).toContain(phrase); for(const p of [b.buildRefineContinuation('out.md',false,false),b.buildRefineContinuation('out.md')]) expect(p.split('#### dependency-minimization')[1].split('#### ')[0]).not.toContain(phrase); });
  test('AC-53: repair prompt describes every violation and destination', async () => {const b=await builder(); const {formatSpecStructureViolation:f}=await structure(); const v=[{kind:'missing-story',storyId:'US-004'},{kind:'orphan-modifies',storyId:'US-004',path:'apps/api/tests/test_count.py'}]; const p=b.buildSpecStructureRepair(v,'/out/plan.md'); for(const item of v) expect(p).toContain(f(item)); expect(p).toContain('Your PRD does not match the story structure the spec declares. The spec\'s stories are binding.'); expect(p).toMatch(/move each acceptance criterion back to the story/i); expect(p).toMatch(/workdir.*dependencies.*Binding Story Structure/is); expect(p).toContain('never merge, split or rename a spec story'); expect(p).toMatch(/\/out\/plan\.md[\s\S]*brief confirmation/i); });
  test('AC-54: heal step issues exactly one matching corrective prompt', async () => {const {specStructureSelfHealStep}=await import('../../../src/operations/plan'); const {findSpecStructureViolations,backfillSpecWorkdirs,extractSpecStructure}=await structure(); const prd=validDraft('US-001','US-002','US-003','US-005'); const violations=findSpecStructureViolations(backfillSpecWorkdirs(prd,extractSpecStructure(five)).prd,five); const b=await builder(); const repair=b.buildSpecStructureRepair(violations,'/out/plan.md'); const send=mock(async()=>({output:'fixed',estimatedCostUsd:0})); const ctx={input:{specContent:five,featureName:'f',branchName:'feat/f',outputPath:'/out/plan.md'},send}; await specStructureSelfHealStep(b,async()=>JSON.stringify(prd)).run(ctx); expect(send).toHaveBeenCalledTimes(1); expect(send).toHaveBeenCalledWith(repair); });
  test('AC-55: absent or malformed draft never triggers repair', async () => {const {specStructureSelfHealStep}=await import('../../../src/operations/plan'); for(const value of [null,'not-json']) {const send=mock(async()=>({output:'fixed'})); await specStructureSelfHealStep(await builder(),async()=>value).run({input:{specContent:five,featureName:'f',branchName:'feat/f',outputPath:'/out/plan.md'},send}); expect(send).not.toHaveBeenCalled();} });
  test('AC-56: interactive hop sends seed then one structure repair', async () => {const {planInteractiveOp,_planInteractiveDeps}=await import('../../../src/operations/plan'); const {findSpecStructureViolations}=await structure(); const draft=validDraft('US-001','US-002','US-003','US-005'); const old=_planInteractiveDeps.readFile; const seed={output:'seed',estimatedCostUsd:0}; const parse=mock(async()=>seed); const send=mock(async()=>({output:'repaired',estimatedCostUsd:0})); try {_planInteractiveDeps.readFile=async()=>JSON.stringify(draft); await planInteractiveOp.hopBody('initial',{input:{specContent:five,featureName:'f',branchName:'feat/f',outputPath:'/out/plan.md'},sendWithParseRetry:parse,send}); expect(parse).toHaveBeenCalledTimes(1); expect(parse).toHaveBeenCalledWith('initial'); expect(send).toHaveBeenCalledTimes(1); expect(send).toHaveBeenCalledWith((await builder()).buildSpecStructureRepair(findSpecStructureViolations(draft,five),'/out/plan.md'));} finally {_planInteractiveDeps.readFile=old;} });
  test('AC-57: no declared stories yields seed without repair', async () => {const {planInteractiveOp}=await import('../../../src/operations/plan'); const seed={output:'seed',estimatedCostUsd:0}; const parse=mock(async()=>seed); const send=mock(async()=>seed); expect(await planInteractiveOp.hopBody('initial',{input:{specContent:'## Overview',featureName:'f',branchName:'feat/f',outputPath:'/out/plan.md'},sendWithParseRetry:parse,send})).toEqual(seed); expect(parse).toHaveBeenCalledTimes(1); expect(parse).toHaveBeenCalledWith('initial'); expect(send).not.toHaveBeenCalled(); });
  test('AC-58: refine repairs structure before out of scope', async () => {const {planRefineOp,_planRefineDeps}=await import('../../../src/operations/plan-refine'); const old=_planRefineDeps.readFile; const input={specContent:`${five}\n## Out of Scope\n- Rewrite scheduler`,featureName:'f',branchName:'feat/f',outputPath:'/out/plan.md',codebaseContext:''}; const draft=validDraft('US-001','US-002','US-003','US-005'); const calls:string[]=[]; try {_planRefineDeps.readFile=async()=>JSON.stringify(draft); const send=mock(async(p:string)=>{calls.push(p);return {output:'ok',estimatedCostUsd:0};}); await planRefineOp.hopBody('initial',{input,sendWithParseRetry:mock(async()=>({output:'seed'})),send}); const b=await builder(); expect(calls[0]).toBe(b.buildRefineContinuation(input.outputPath,false,true)); expect(calls[1]).toBe(b.buildSpecStructureRepair((await structure()).findSpecStructureViolations(draft,input.specContent),input.outputPath)); expect(calls[2]).toBe(b.buildOutOfScopeRepair((await import('../../../src/prd')).findMissingOutOfScope(draft,input.specContent),input.outputPath)); expect(calls).toHaveLength(3); } finally {_planRefineDeps.readFile=old;} });
  test('AC-59: refine continuation protects binding dependencies', async () => {const {planRefineOp}=await import('../../../src/operations/plan-refine'); const calls:string[]=[]; await planRefineOp.hopBody('initial',{input:{specContent:declared,featureName:'f',branchName:'feat/f',outputPath:'/out/plan.md',codebaseContext:''},sendWithParseRetry:mock(async()=>({output:'seed'})),send:mock(async(p:string)=>{calls.push(p);return {output:'ok'};})}); expect(calls[0]).toBe((await builder()).buildRefineContinuation('/out/plan.md',false,true)); expect(calls[0]).toContain('Never add or remove a dependency of a story the Binding Story Structure lists, and never merge, split or rename one of its stories.'); });
  test('AC-60: persistent mismatch triggers only one structure repair', async () => {const {planInteractiveOp,_planInteractiveDeps}=await import('../../../src/operations/plan'); const old=_planInteractiveDeps.readFile; const send=mock(async()=>({output:'still broken'})); try {_planInteractiveDeps.readFile=async()=>JSON.stringify(validDraft('US-001','US-002','US-003','US-005')); await planInteractiveOp.hopBody('initial',{input:{specContent:five,featureName:'f',branchName:'feat/f',outputPath:'/out/plan.md'},sendWithParseRetry:mock(async()=>({output:'seed'})),send}); expect(send).toHaveBeenCalledTimes(1); } finally {_planInteractiveDeps.readFile=old;} });
  test('AC-61: interactive repair accumulates turn costs', async () => {const {planInteractiveOp,_planInteractiveDeps}=await import('../../../src/operations/plan'); const old=_planInteractiveDeps.readFile; try {_planInteractiveDeps.readFile=async()=>JSON.stringify(validDraft('US-001')); const r=await planInteractiveOp.hopBody('initial',{input:{specContent:spec('**US-001: A**','**US-004: B**'),featureName:'f',branchName:'feat/f',outputPath:'/out/plan.md'},sendWithParseRetry:mock(async()=>({output:'seed',estimatedCostUsd:0.2})),send:mock(async()=>({output:'repair',estimatedCostUsd:0.1}))}); expect(r.estimatedCostUsd).toBeCloseTo(0.3); } finally {_planInteractiveDeps.readFile=old;} });
});

async function planContext(specContent: string, writeFile = async (_p: string,_s: string) => {}) {
  const {planConfigSelector}=await import('../../../src/config');
  const {makeMockRuntime,makeLogger}=await import('../../../test/helpers');
  return {workdir:root,naxDir:'/repo/.nax',outputDir:'/repo/.nax/features/f',outputPath:'/repo/.nax/features/f/prd.json',specContent,codebaseContext:'',normalizedRoots:[],relativePackages:[],packageDetails:[],projectName:'p',branchName:'feat/f',timeoutSeconds:60,config:planConfigSelector.select(makeNaxConfig()),profileName:undefined,options:{from:'spec.md',feature:'f'},runtime:makeMockRuntime(),interactionChain:null,interactionBridge:{},deps:{readFile:async()=>'',writeFile,mkdirp:async()=>{},existsSync:()=>true,readPackageJson:async()=>null,readPackageJsonAt:async()=>null,scanSourceRoots:async()=>[],spawnSync:()=>({stdout:Buffer.from(''),exitCode:0}),initInteractionChain:async()=>null,createInteractionBridge:()=>({}),getLogger:()=>makeLogger()}};
}