import { test, expect, mock } from 'bun:test';
import { mkdtemp, writeFile, chmod, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const req = (command: string) => ({ kind: 'shell' as const, command, cwd: '/repo', site: 'bash' as const });
const rewritten = (command: string) => ({ kind: 'rewritten' as const, command, provider: 'rtk' });
const shell = async () => import('@/execution/command-interceptor/shell');
const rtk = async () => import('@/execution/interceptors/rtk');
const deps = (rewrite: ReturnType<typeof mock> = mock(async () => ({ exitCode: 3, stdout: 'rtk bun test', timedOut: false })), which: () => string | null = () => '/bin/rtk') => ({ rewrite, which, version: () => '1.0', record: mock(() => {}) });
const provider = async (d: ReturnType<typeof deps>, options: { enabled?: boolean; bash?: boolean } = {}) => (await rtk()).createRtkInterceptor({ enabled: options.enabled ?? true, verbs: [], bash: options.bash ?? true, _deps: d });
const shellReq = { command: 'bun test', cwd: '/tmp' };
const ctx = { root: '/tmp', resolvedPaths: [], maxBytes: 40000, maxFileBytes: 2000000 };
const launchResult = (stdout = 'body', exitCode = 0) => ({ stdout, stderr: '', exitCode, timedOut: false, executed: ['/bin/sh', '-c', 'bun test'], sandbox: { backend: 'none' as const, wrapped: false } });

 test('AC-1: simple bun prefix rewrite', async () => { expect((await shell()).validateShellRewrite(req('bun test a.test.ts'), rewritten('rtk bun test a.test.ts'))).toEqual(rewritten('rtk bun test a.test.ts')); });
 test('AC-2: preserve assignment prefix', async () => { expect((await shell()).validateShellRewrite(req('FOO=1 bun test'), rewritten('FOO=1 rtk bun test'))).toEqual(rewritten('FOO=1 rtk bun test')); });
 test('AC-3: prefix both semicolon segments', async () => { expect((await shell()).validateShellRewrite(req('bun test; git status'), rewritten('rtk bun test; rtk git status'))).toEqual(rewritten('rtk bun test; rtk git status')); });
 test('AC-4: preserve cd and rewrite right side', async () => { expect((await shell()).validateShellRewrite(req('cd pkg && bun test'), rewritten('cd pkg && rtk bun test'))).toEqual(rewritten('cd pkg && rtk bun test')); });
 test('AC-5: decline changed verb', async () => { const result = (await shell()).validateShellRewrite(req('cat src/a.ts'), rewritten('rtk read src/a.ts')); expect(result.kind).toBe('declined'); expect(typeof result.reason).toBe('string'); expect(result.reason.length).toBeGreaterThan(0); });
 test('AC-6: decline normalized operator spacing', async () => { expect((await shell()).validateShellRewrite(req('cd pkg&&bun test'), rewritten('cd pkg && rtk bun test')).kind).toBe('declined'); });
 test('AC-7: decline insertion inside uv run', async () => { expect((await shell()).validateShellRewrite(req('uv run pytest -q'), rewritten('uv run rtk pytest -q')).kind).toBe('declined'); });
 test('AC-8: decline pipeline', async () => { expect((await shell()).validateShellRewrite(req('git log --oneline | head -5'), rewritten('rtk git log --oneline | head -5')).kind).toBe('declined'); });
 test('AC-9: decline quote replacement', async () => { expect((await shell()).validateShellRewrite(req("bun test 'a b.ts'"), rewritten('rtk bun test "a b.ts"')).kind).toBe('declined'); });
 test('AC-10: decline double prefix', async () => { expect((await shell()).validateShellRewrite(req('rtk bun test'), rewritten('rtk rtk bun test')).kind).toBe('declined'); });
 test('AC-11: decline appended command', async () => { expect((await shell()).validateShellRewrite(req('bun test'), rewritten('rtk bun test; rm -rf .')).kind).toBe('declined'); });
 test('AC-12: decline pipeline segment injection', async () => { expect((await shell()).validateShellRewrite(req('cat x | grep y'), rewritten('cat x | rtk grep y')).kind).toBe('declined'); });
 test('AC-13: decline command substitution', async () => { expect((await shell()).validateShellRewrite(req('bun test $(id)'), rewritten('rtk bun test $(id)')).kind).toBe('declined'); });
 test('AC-14: identical command is unchanged', async () => { expect((await shell()).validateShellRewrite(req('bun test'), rewritten('bun test'))).toEqual({ kind: 'unchanged' }); });
 test('AC-15: passthrough unchanged and declined without mutation', async () => { for (const result of [{ kind: 'unchanged' as const }, { kind: 'declined' as const, reason: 'some reason' }]) { const snapshot = structuredClone(result); expect((await shell()).validateShellRewrite(req('bun test'), result)).toEqual(snapshot); expect(result).toEqual(snapshot); } });
 test('AC-16: missing interceptor is passthrough', async () => { expect(await (await shell()).interceptShell('bun test', '/repo', undefined)).toEqual({ command: 'bun test', rewritten: false }); });
 test('AC-17: missing method is passthrough', async () => { expect(await (await shell()).interceptShell('bun test', '/repo', { interceptShell: undefined })).toEqual({ command: 'bun test', rewritten: false }); });
 test('AC-18: interceptor receives shell request', async () => { const spy = mock(async () => ({ kind: 'unchanged' as const })); await (await shell()).interceptShell('bun test', '/repo', { interceptShell: spy }); expect(spy).toHaveBeenCalledTimes(1); expect(spy).toHaveBeenCalledWith(req('bun test')); });
 test('AC-19: valid intercepted rewrite is returned', async () => { expect(await (await shell()).interceptShell('bun test', '/repo', { interceptShell: mock(async () => rewritten('rtk bun test')) })).toEqual({ command: 'rtk bun test', provider: 'rtk', rewritten: true }); });
 test('AC-20: invalid intercepted rewrite falls back', async () => { expect(await (await shell()).interceptShell('bun test', '/repo', { interceptShell: mock(async () => rewritten('rtk read src/a.ts')) })).toEqual({ command: 'bun test', rewritten: false }); });
 test('AC-21: interceptor exception falls back', async () => { expect(await (await shell()).interceptShell('bun test', '/repo', { interceptShell: mock(async () => { throw new Error('boom'); }) })).toEqual({ command: 'bun test', rewritten: false }); });
 test('AC-22: barrel reexports shell seam by identity', async () => { const barrel = await import('@/execution/command-interceptor'); const seam = await shell(); expect(typeof barrel.interceptShell).toBe('function'); expect(typeof barrel.validateShellRewrite).toBe('function'); expect(barrel.interceptShell).toBe(seam.interceptShell); expect(barrel.validateShellRewrite).toBe(seam.validateShellRewrite); });
 test('AC-23: schema defaults bash off', async () => { const { ExecutionConfigSchema } = await import('@/config/schemas-execution'); expect(ExecutionConfigSchema.parse({}).commandInterceptor.bash.enabled).toBe(false); });
 test('AC-24: default config has bash off', async () => { const { DEFAULT_CONFIG } = await import('@/config'); expect(DEFAULT_CONFIG.execution.commandInterceptor.bash.enabled).toBe(false); });
 test('AC-25: enabled parent and bash parse', async () => { const { ExecutionConfigSchema } = await import('@/config/schemas-execution'); expect(ExecutionConfigSchema.parse({ commandInterceptor: { enabled: true, bash: { enabled: true } } }).commandInterceptor.bash.enabled).toBe(true); });
 test('AC-26: bash requires enabled parent', async () => { const { ExecutionConfigSchema } = await import('@/config/schemas-execution'); const parsed = ExecutionConfigSchema.safeParse({ commandInterceptor: { enabled: false, bash: { enabled: true } } }); expect(parsed.success).toBe(false); if (!parsed.success) expect(parsed.error.issues.map(i => i.message)).toContain('execution.commandInterceptor.bash.enabled requires execution.commandInterceptor.enabled'); });
 test('AC-27: bash config refuses unknown keys', async () => { const { ExecutionConfigSchema } = await import('@/config/schemas-execution'); const parsed = ExecutionConfigSchema.safeParse({ commandInterceptor: { enabled: true, bash: { enabled: true, unexpected: true } } }); expect(parsed.success).toBe(false); if (!parsed.success) expect(parsed.error.issues.some(i => i.code === 'unrecognized_keys' && i.path.join('.') === 'commandInterceptor.bash')).toBe(true); });
 test('AC-28: bash flag has a description', async () => { const { FIELD_DESCRIPTIONS } = await import('@/cli/config-descriptions'); const value = FIELD_DESCRIPTIONS['execution.commandInterceptor.bash.enabled']; expect(typeof value).toBe('string'); expect(value.trim().length).toBeGreaterThan(0); });
 test('AC-29: exit 3 and newline indicate rewrite', async () => { const d = deps(mock(async () => ({ exitCode: 3, stdout: 'rtk bun test\n', timedOut: false }))); expect(await (await provider(d)).interceptShell(shellReq)).toEqual(rewritten('rtk bun test')); expect(d.rewrite).toHaveBeenCalledTimes(1); expect(d.rewrite).toHaveBeenCalledWith('bun test', '/tmp'); });
 test('AC-30: exit 0 with rewrite is accepted', async () => { const d = deps(mock(async () => ({ exitCode: 0, stdout: 'rtk bun test', timedOut: false }))); expect(await (await provider(d)).interceptShell(shellReq)).toEqual(rewritten('rtk bun test')); });
 test('AC-31: exit 1 is unchanged', async () => { expect(await (await provider(deps(mock(async () => ({ exitCode: 1, stdout: '', timedOut: false }))))).interceptShell(shellReq)).toEqual({ kind: 'unchanged' }); });
 test('AC-32: exit 3 with same command is unchanged', async () => { expect(await (await provider(deps(mock(async () => ({ exitCode: 3, stdout: 'bun test', timedOut: false }))))).interceptShell(shellReq)).toEqual({ kind: 'unchanged' }); });
 test('AC-33: exit 3 with empty output is unchanged', async () => { expect(await (await provider(deps(mock(async () => ({ exitCode: 3, stdout: '', timedOut: false }))))).interceptShell(shellReq)).toEqual({ kind: 'unchanged' }); });
 test('AC-34: exit 2 declines', async () => { expect(await (await provider(deps(mock(async () => ({ exitCode: 2, stdout: '', timedOut: false }))))).interceptShell(shellReq)).toEqual({ kind: 'declined', reason: 'rtk rewrite exited 2' }); });
 test('AC-35: exit 127 declines', async () => { expect(await (await provider(deps(mock(async () => ({ exitCode: 127, stdout: '', timedOut: false }))))).interceptShell(shellReq)).toEqual({ kind: 'declined', reason: 'rtk rewrite exited 127' }); });
 test('AC-36: rewrite timeout declines', async () => { expect(await (await provider(deps(mock(async () => ({ exitCode: -1, stdout: '', timedOut: true }))))).interceptShell(shellReq)).toEqual({ kind: 'declined', reason: 'rtk rewrite timed out' }); });
 test('AC-37: rewrite spawn rejection declines', async () => { expect(await (await provider(deps(mock(async () => { throw new Error('spawn ENOENT'); })))).interceptShell(shellReq)).toEqual({ kind: 'declined', reason: 'rtk rewrite failed: spawn ENOENT' }); });
 test('AC-38: disabled bash does not call rewrite', async () => { const d = deps(); expect(await (await provider(d, { bash: false })).interceptShell(shellReq)).toEqual({ kind: 'unchanged' }); expect(d.rewrite).not.toHaveBeenCalled(); });
 test('AC-39: disabled interceptor does not call rewrite', async () => { const d = deps(); expect(await (await provider(d, { enabled: false })).interceptShell(shellReq)).toEqual({ kind: 'unchanged' }); expect(d.rewrite).not.toHaveBeenCalled(); });
 test('AC-40: missing rtk binary declines without rewriting', async () => { const d = deps(undefined, () => null); expect(await (await provider(d)).interceptShell(shellReq)).toEqual({ kind: 'declined', reason: 'rtk binary not found on PATH' }); expect(d.rewrite).not.toHaveBeenCalled(); });
 test('AC-41: probe exception declines', async () => { const d = deps(undefined, () => { throw new Error('boom'); }); expect(await (await provider(d)).interceptShell(shellReq)).toEqual({ kind: 'declined', reason: 'rtk probe failed: boom' }); });
 test('AC-42: state records bash enabled', async () => { const d = deps(); await provider(d); expect(d.record.mock.calls[0][0].bash).toBe(true); });
 test('AC-43: state records bash disabled by default', async () => { const d = deps(); (await rtk()).createRtkInterceptor({ enabled: true, verbs: [], _deps: d }); expect(d.record.mock.calls[0][0].bash).toBe(false); });

async function withFakeRtk(script: string, fn: (dir: string) => Promise<void>) { const dir = await mkdtemp(join(tmpdir(), 'nax-rtk-')); const path = process.env.PATH; try { await writeFile(join(dir, 'rtk'), '#!/bin/sh\n' + script + '\n'); await chmod(join(dir, 'rtk'), 0o755); process.env.PATH = dir + ':' + path; await fn(dir); } finally { process.env.PATH = path; await rm(dir, { recursive: true, force: true }); } }
 test('AC-44: default rewrite times out promptly', async () => { const { defaultRewrite, RTK_REWRITE_TIMEOUT_MS } = await rtk(); expect(RTK_REWRITE_TIMEOUT_MS).toBe(2000); await withFakeRtk('echo $$ > "$PID_FILE"\nexec sleep 20', async dir => { const pidFile = join(dir, 'pid'); const old = process.env.PID_FILE; process.env.PID_FILE = pidFile; try { const start = Date.now(); const result = await defaultRewrite('bun test', '/tmp'); expect(result).toMatchObject({ timedOut: true, exitCode: -1, stdout: '' }); expect(Date.now() - start).toBeLessThanOrEqual(RTK_REWRITE_TIMEOUT_MS + 1000); expect(Number((await readFile(pidFile, 'utf8')).trim())).toBeGreaterThan(0); } finally { process.env.PID_FILE = old; } }); });
 test('AC-45: timeout kills the child process', async () => { const { defaultRewrite } = await rtk(); await withFakeRtk('echo $$ > "$PID_FILE"\nexec sleep 20', async dir => { const file = join(dir, 'pid'), old = process.env.PID_FILE; process.env.PID_FILE = file; try { expect((await defaultRewrite('bun test', '/tmp')).timedOut).toBe(true); const pid = Number((await readFile(file, 'utf8')).trim()); expect(pid).toBeGreaterThan(0); try { process.kill(pid, 0); throw new Error('child still alive'); } catch (error) { expect((error as NodeJS.ErrnoException).code).toBe('ESRCH'); } } finally { process.env.PID_FILE = old; } }); });
 test('AC-46: default rewrite captures exit 3 and stdout', async () => { const { defaultRewrite } = await rtk(); await withFakeRtk('if [ "$1 $2 $3" = "rewrite bun test" ]; then printf "rtk bun test\\n"; exit 3; fi\nexit 9', async () => { expect(await defaultRewrite('bun test', '/tmp')).toEqual({ exitCode: 3, stdout: 'rtk bun test\n', timedOut: false }); }); });

async function runtimeFixture(patterns = ['bun test*'], interceptor: any = { interceptShell: mock(async () => rewritten('rtk bun test a.test.ts')) }, stdout = 'body', exitCode = 0) { const { compileToolPolicy } = await import('@/tools/policy'); const { createCodingToolRuntime } = await import('@/tools/runtime'); const { createBashTool, _bashToolDeps } = await import('@/tools/bash'); const old = { ..._bashToolDeps }; const calls: any[] = []; const sinkCalls: any[] = []; _bashToolDeps.interceptor = interceptor === null ? undefined : interceptor; _bashToolDeps.runArgv = mock(async (options: any) => { calls.push(options); return { stdout, stderr: '', exitCode, timedOut: false }; }); const root = process.cwd(); const runtime = createCodingToolRuntime({ policy: compileToolPolicy([{ tool: 'Bash', patterns }], root), extraTools: [createBashTool()], sink: { record: (x: any) => sinkCalls.push(x), flush: async () => {} } as any }); return { runtime, calls, sinkCalls, root, interceptor, restore: () => Object.assign(_bashToolDeps, old) }; }
 test('AC-47: granted rewrite executes rewritten argv once', async () => { const f = await runtimeFixture(); try { await f.runtime.callTool('Bash', { command: 'bun test a.test.ts' }); expect(f.calls).toHaveLength(1); expect(f.calls[0].argv).toEqual(['/bin/sh', '-c', 'rtk bun test a.test.ts']); } finally { f.restore(); } });
 test('AC-48: interception gets original and root', async () => { const f = await runtimeFixture(); try { await f.runtime.callTool('Bash', { command: 'bun test a.test.ts' }); expect(f.interceptor.interceptShell).toHaveBeenCalledWith('bun test a.test.ts', f.root); } finally { f.restore(); } });
 test('AC-49: denied command never spawns', async () => { const f = await runtimeFixture(); try { const result = await f.runtime.callTool('Bash', { command: 'rm -rf src' }); expect(result.kind).toBe('denied'); expect(result.isError).toBe(true); expect(f.calls).toHaveLength(0); } finally { f.restore(); } });
 test('AC-50: denied command never invokes interceptor', async () => { const f = await runtimeFixture(); try { await f.runtime.callTool('Bash', { command: 'rm -rf src' }); expect(f.interceptor.interceptShell).not.toHaveBeenCalled(); } finally { f.restore(); } });
 test('AC-51: audit captures rewritten argv', async () => { const f = await runtimeFixture(); try { const result = await f.runtime.callTool('Bash', { command: 'bun test a.test.ts' }); expect(result.audit?.executed ?? f.sinkCalls[0]?.executed).toEqual(['/bin/sh', '-c', 'rtk bun test a.test.ts']); } finally { f.restore(); } });
 test('AC-52: invalid rewrite executes original command', async () => { const f = await runtimeFixture(['cat *'], { interceptShell: mock(async () => rewritten('rtk read src/a.ts')) }); try { await f.runtime.callTool('Bash', { command: 'cat src/a.ts' }); expect(f.calls[0].argv).toEqual(['/bin/sh', '-c', 'cat src/a.ts']); } finally { f.restore(); } });
 test('AC-53: no interceptor executes original', async () => { const f = await runtimeFixture(['echo *'], null); try { await f.runtime.callTool('Bash', { command: 'echo original' }); expect(f.calls[0].argv).toEqual(['/bin/sh', '-c', 'echo original']); } finally { f.restore(); } });
 test('AC-54: no interceptor audits original', async () => { const f = await runtimeFixture(['echo *'], null); try { const result = await f.runtime.callTool('Bash', { command: 'echo original' }); expect(result.audit?.executed ?? f.sinkCalls[0]?.executed).toEqual(['/bin/sh', '-c', 'echo original']); } finally { f.restore(); } });
 test('AC-55: launcher sees rewritten shell spec', async () => { const { createBashTool, _bashToolDeps } = await import('@/tools/bash'); const old = _bashToolDeps.interceptor; _bashToolDeps.interceptor = { interceptShell: mock(async () => rewritten('rtk bun test a.test.ts')) }; const run = mock(async () => launchResult()); try { await createBashTool({ launcher: { state: { kind: 'disabled' }, run } }).run({ command: 'bun test a.test.ts' }, ctx); expect(run.mock.calls[0][0].spec).toEqual({ kind: 'shell', shell: '/bin/sh', command: 'rtk bun test a.test.ts' }); } finally { _bashToolDeps.interceptor = old; } });
 test('AC-56: rewritten output strips trailing recall hint', async () => { const f = await runtimeFixture(['bun test*'], { interceptShell: mock(async () => rewritten('rtk bun test a.test.ts')), postProcess: (_: string) => ({ output: 'body' }) }, 'body\n[full output: rtk recall 12]'); try { const result = await f.runtime.callTool('Bash', { command: 'bun test a.test.ts' }); expect(result.content).toBe('exit 0\nbody\n'); } finally { f.restore(); } });
 test('AC-57: non-rewritten output retains recall hint', async () => { const f = await runtimeFixture(['echo *'], null, 'body\n[full output: rtk recall 12]'); try { const result = await f.runtime.callTool('Bash', { command: 'echo test' }); expect(result.content).toContain('body\n[full output: rtk recall 12]'); } finally { f.restore(); } });
 test('AC-58: postProcess receives original shell request', async () => { const postProcess = mock((s: string) => ({ output: s })); const f = await runtimeFixture(['bun test*'], { interceptShell: mock(async () => rewritten('rtk bun test a.test.ts')), postProcess }); try { await f.runtime.callTool('Bash', { command: 'bun test a.test.ts' }); expect(postProcess).toHaveBeenCalledTimes(1); expect(postProcess.mock.calls[0][1]).toEqual({ ...req('bun test a.test.ts'), cwd: f.root }); } finally { f.restore(); } });
 test('AC-59: postProcess error preserves raw stdout', async () => { const f = await runtimeFixture(['bun test*'], { interceptShell: mock(async () => rewritten('rtk bun test a.test.ts')), postProcess: () => { throw Error('modified'); } }, 'original raw stdout'); try { const result = await f.runtime.callTool('Bash', { command: 'bun test a.test.ts' }); expect(result.content).toContain('original raw stdout'); expect(result.content).not.toContain('modified'); } finally { f.restore(); } });
 test('AC-60: rewritten failure retains exit status', async () => { const f = await runtimeFixture(['bun test*'], undefined, 'failed', 1); try { const result = await f.runtime.callTool('Bash', { command: 'bun test a.test.ts' }); expect(result.isError ?? result.kind === 'error').toBe(true); expect(result.audit?.exitCode ?? f.sinkCalls[0]?.exitCode).toBe(1); } finally { f.restore(); } });
 test('AC-61: rewritten failure never retries original', async () => { const f = await runtimeFixture(['bun test*'], undefined, 'failed', 1); try { await f.runtime.callTool('Bash', { command: 'bun test a.test.ts' }); expect(f.calls).toHaveLength(1); expect(f.calls[0].argv).toEqual(['/bin/sh', '-c', 'rtk bun test a.test.ts']); } finally { f.restore(); } });

async function setupFixture(configOverride: any = {}) { const helpers = await import('@test/helpers'); const { setupRun, _runSetupDeps } = await import('@/execution/lifecycle/run-setup'); const { _bashToolDeps } = await import('@/tools/bash'); const { _gitToolDeps } = await import('@/tools/git'); const dir = await mkdtemp(join(tmpdir(), 'nax-rtk-setup-')); const old = { ..._runSetupDeps }; const oldBash = _bashToolDeps.interceptor, oldGit = _gitToolDeps.interceptor; const runtimes: any[] = []; const prdPath = join(dir, 'prd.json'); await writeFile(prdPath, JSON.stringify(helpers.makePRD({ feature: 'ci-drive', userStories: [] }))); _runSetupDeps.createRuntime = (() => { const runtime = helpers.makeMockRuntime({ workdir: dir }); runtimes.push(runtime); return runtime; }) as any; _runSetupDeps.installCrashHandlers = (() => () => {}) as any; _runSetupDeps.detectProjectProfile = (async () => ({})) as any; const config = helpers.makeNaxConfig({ execution: { commandInterceptor: configOverride } }); const options = { prdPath, workdir: dir, config, hooks: { hooks: {} }, feature: 'ci-drive', dryRun: true, statusFile: join(dir, 'status.json'), runId: `rtk-accept-${Date.now()}`, startedAt: new Date().toISOString(), startTime: Date.now(), skipPrecheck: true, headless: true, formatterMode: 'quiet', getTotalCost: () => 0, getIterations: () => 0, getStoriesCompleted: () => 0, getTotalStories: () => 0 }; return { dir, setup: () => setupRun(options as any), cleanup: async () => { Object.assign(_runSetupDeps, old); _bashToolDeps.interceptor = oldBash; _gitToolDeps.interceptor = oldGit; await Promise.allSettled(runtimes.map(r => r.close())); await rm(dir, { recursive: true, force: true }); } }; }
 test('AC-62: setup shares one interceptor between Bash and Git', async () => { const f = await setupFixture({ enabled: true, bash: { enabled: true } }); try { await f.setup().catch(() => {}); const { _bashToolDeps } = await import('@/tools/bash'); const { _gitToolDeps } = await import('@/tools/git'); expect(_bashToolDeps.interceptor).toBeDefined(); expect(_bashToolDeps.interceptor).toBe(_gitToolDeps.interceptor); } finally { await f.cleanup(); } });
 test('AC-63: setup logs enabled Bash interceptor state', async () => { const f = await setupFixture({ enabled: true, bash: { enabled: true } }); const logger = await import('@/logger'); const original = logger.getSafeLogger(); const records: any[] = []; const oldInfo = original?.info; if (original) original.info = ((...args: any[]) => { records.push(args); }) as any; try { await f.setup().catch(() => {}); const row = records.find(row => row[1] === 'rtk interceptor state' || row[0] === 'rtk interceptor state'); expect(row).toBeDefined(); expect(row[2].bash).toBe(true); } finally { if (original && oldInfo) original.info = oldInfo; await f.cleanup(); } });
 test('AC-64: default setup interceptShell is unchanged', async () => { const f = await setupFixture(); try { await f.setup().catch(() => {}); const { _bashToolDeps } = await import('@/tools/bash'); expect(_bashToolDeps.interceptor).toBeDefined(); expect(await _bashToolDeps.interceptor.interceptShell('bun test', f.dir)).toEqual({ kind: 'unchanged' }); } finally { await f.cleanup(); } });

async function overlayFixture(environment: Record<string,string>, stripped: string[] = []) { const env = await import('@/utils/agent-output-env'); const previous = env._agentOutputEnvDeps.processEnv; env._agentOutputEnvDeps.processEnv = () => environment; return { value: env.agentOutputOverlay(stripped), restore: () => { env._agentOutputEnvDeps.processEnv = previous; } }; }
 test('AC-65: empty environment gets agent overlay', async () => { const f = await overlayFixture({}); try { expect(f.value).toEqual({ AGENT: '1' }); } finally { f.restore(); } });
 test('AC-66: inherited CLAUDECODE disables overlay', async () => { const f = await overlayFixture({ CLAUDECODE: '1' }); try { expect(f.value).toBeUndefined(); } finally { f.restore(); } });
 test('AC-67: inherited AGENT zero disables overlay', async () => { const f = await overlayFixture({ AGENT: '0' }); try { expect(f.value).toBeUndefined(); } finally { f.restore(); } });
 test('AC-68: explicit AGENT stripping disables overlay', async () => { const f = await overlayFixture({}, ['AGENT']); try { expect(f.value).toBeUndefined(); } finally { f.restore(); } });
 test('AC-69: verification barrel reexports agent output helpers by identity', async () => { const { withAgentOutputEnv: reexportedWith, AGENT_OUTPUT_MARKERS: reexportedMarkers } = await import('@/verification'); const { withAgentOutputEnv: sourceWith, AGENT_OUTPUT_MARKERS: sourceMarkers } = await import('../../../src/utils/agent-output-env'); expect(reexportedWith).toBe(sourceWith); expect(reexportedMarkers).toBe(sourceMarkers); });
async function bashEnvFixture(environment: Record<string,string>, options: any = {}) { const env = await import('@/utils/agent-output-env'); const { _bashToolDeps, createBashTool } = await import('@/tools/bash'); const previous = env._agentOutputEnvDeps.processEnv, oldRun = _bashToolDeps.runArgv, oldInterceptor = _bashToolDeps.interceptor; env._agentOutputEnvDeps.processEnv = () => environment; _bashToolDeps.interceptor = undefined; const run = mock(async () => ({ stdout: 'ok', stderr: '', exitCode: 0, timedOut: false })); _bashToolDeps.runArgv = run as any; return { tool: createBashTool(options), run, restore: () => { env._agentOutputEnvDeps.processEnv = previous; _bashToolDeps.runArgv = oldRun; _bashToolDeps.interceptor = oldInterceptor; } }; }
 test('AC-70: direct Bash spawn receives AGENT overlay', async () => { const f = await bashEnvFixture({}); try { await f.tool.run({ command: 'bun test' }, ctx); expect(f.run.mock.calls[0][0].env).toEqual({ AGENT: '1' }); } finally { f.restore(); } });
 test('AC-71: inherited marker leaves Bash spawn env absent', async () => { const f = await bashEnvFixture({ CLAUDECODE: '1' }); try { await f.tool.run({ command: 'bun test' }, ctx); expect(Object.hasOwn(f.run.mock.calls[0][0], 'env')).toBe(false); } finally { f.restore(); } });
 test('AC-72: stripped AGENT leaves Bash spawn env absent', async () => { const f = await bashEnvFixture({}, { stripEnvVars: ['AGENT'] }); try { await f.tool.run({ command: 'bun test' }, ctx); expect(Object.hasOwn(f.run.mock.calls[0][0], 'env')).toBe(false); } finally { f.restore(); } });
 test('AC-73: Bash launcher receives agent env', async () => { const run = mock(async () => launchResult()); const f = await bashEnvFixture({}, { launcher: { state: { kind: 'disabled' }, run } }); try { await f.tool.run({ command: 'echo test' }, ctx); expect(run.mock.calls[0][0].env).toEqual({ AGENT: '1' }); } finally { f.restore(); } });
async function execFixture(environment: Record<string,string>, launcher?: any) { const env = await import('@/utils/agent-output-env'); const previous = env._agentOutputEnvDeps.processEnv; env._agentOutputEnvDeps.processEnv = () => environment; const { runExecBranch } = await import('@/tools/run-command-exec'); const { _argvExecDeps } = await import('@/utils/argv-exec'); const old = _argvExecDeps.spawn; const run = mock((argv: any, options: any) => Bun.spawn(['/bin/sh', '-c', 'true'], { ...options, cwd: '/tmp' })); _argvExecDeps.spawn = run as any; const opts = { exec: { repoRoot: '/tmp', packageWorkdir: '/tmp', allowScripts: false, patterns: ['bun test*'], ...(launcher ? { launcher } : {}) } }; return { run: (input: any = { argv: ['bun', 'test'] }) => runExecBranch(input, ctx, opts as any), spawn: run, restore: () => { env._agentOutputEnvDeps.processEnv = previous; _argvExecDeps.spawn = old; } }; }
 test('AC-74: direct Exec spawn receives agent env', async () => { const f = await execFixture({}); try { await f.run(); expect(f.spawn.mock.calls[0][1].env).toEqual({ AGENT: '1' }); } finally { f.restore(); } });
 test('AC-75: Exec launcher merges normalized env and AGENT', async () => { const run = mock(async () => launchResult()); const f = await execFixture({}, { state: { kind: 'disabled' }, run }); try { await f.run({ argv: ['yarn', 'add', 'fixture'], target: 'package' }); expect(run.mock.calls[0][0].env).toEqual({ YARN_ENABLE_SCRIPTS: 'false', AGENT: '1' }); } finally { f.restore(); } });
 test('AC-76: inherited marker leaves Exec spawn env absent', async () => { const f = await execFixture({ CLAUDECODE: '1' }); try { await f.run(); expect(Object.hasOwn(f.spawn.mock.calls[0][1], 'env')).toBe(false); } finally { f.restore(); } });
 test('AC-77: real srt launcher forwards AGENT into Bash', async () => { const { createSrtBackend, probeSandbox, createCommandLauncher } = await import('@/sandbox'); const backend = createSrtBackend({}); const probe = await probeSandbox(backend); if (!probe.available) return; const env = await import('@/utils/agent-output-env'); const prev = env._agentOutputEnvDeps.processEnv; env._agentOutputEnvDeps.processEnv = () => ({}); try { const launcher = createCommandLauncher({ state: { kind: 'available', backend: 'srt', network: {}, sharedTmp: true }, backend, policyFor: async root => ({ writeRoots: [root], denyRead: [], denyWrite: [], network: {} }) }); const { createBashTool } = await import('@/tools/bash'); const output = await createBashTool({ launcher }).run({ command: 'echo AGENT=$AGENT' }, ctx); expect(output.content).toContain('AGENT=1'); } finally { env._agentOutputEnvDeps.processEnv = prev; await backend.reset?.(); } });
 test('AC-78: quality runner subprocess receives AGENT overlay', async () => { const env = await import('@/utils/agent-output-env'); const { _qualityRunnerDeps, runQualityCommand } = await import('@/quality/runner'); const prev = env._agentOutputEnvDeps.processEnv, oldSpawn = _qualityRunnerDeps.spawn; env._agentOutputEnvDeps.processEnv = () => ({}); const calls: any[] = []; _qualityRunnerDeps.spawn = ((argv: any, options: any) => { calls.push(options); return Bun.spawn(['/bin/sh', '-c', 'true'], { ...options, cwd: process.cwd() }); }) as any; try { await runQualityCommand({ commandName: 'test', command: 'true', workdir: process.cwd() }); expect(calls.length).toBeGreaterThan(0); expect(calls[0].env.AGENT).toBe('1'); } finally { env._agentOutputEnvDeps.processEnv = prev; _qualityRunnerDeps.spawn = oldSpawn; } });