import { afterEach, describe, expect, mock, test } from 'bun:test';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';

const plugin = (name: string, register: unknown, provides = ['loop-handlers']) => ({ name, version: '1.0.0', provides, extensions: { loopHandlers: register === undefined ? undefined : { register } } });
const entry = (event: string, handler: (...args: any[]) => any, owner = 'p') => ({ plugin: owner, event, handler });
const call = { id: 'c1', name: 'name', input: {} };
const before = { call, tools: [] };
const after = { content: 'original', isError: false, toolName: 'name', callId: 'c1' };
const context = { sessionName: 'session', role: 'implementer' };
const never = () => new Promise<never>(() => {});
const root = resolve(import.meta.dir, '../../..');
async function logs() {
  const { initLogger, addSink } = await import('@/logger');
  initLogger({ level: 'debug', suppressConsole: true });
  const records: any[] = [];
  const dispose = addSink((record) => records.push(record));
  return { records, dispose, matching: (stage: string, level: string) => records.filter(r => r.stage === stage && r.level === level) };
}
async function external(event: string, handler: (...args: any[]) => any, owner = 'p', signal = new AbortController().signal, getCtx = () => context) {
  const { wrapExternalHandler } = await import('@/agents/native/session/loop-events/external-handler');
  return wrapExternalHandler(entry(event, handler, owner) as any, getCtx, signal) as (payload: any) => Promise<any>;
}
async function withTimeout(ms: number, run: () => Promise<any>) {
  const { _externalHandlerDeps } = await import('@/agents/native/session/loop-events/external-handler');
  const old = _externalHandlerDeps.timeoutMs;
  _externalHandlerDeps.timeoutMs = ms;
  try { return await run(); } finally { _externalHandlerDeps.timeoutMs = old; }
}
const failBlock = (value: any) => {
  expect(value.kind).toBe('block'); expect(value.isError).toBe(true);
  expect(value.content).toMatch(/Blocked: loop handler from plugin 'p' failed/);
};
async function builtin(set: any[], overrides: Record<string, any> = {}) {
  const { createLoopEventRegistry } = await import('@/agents/native/session/loop-events');
  const { registerBuiltinLoopHandlers } = await import('@/agents/native/session/loop-handlers');
  const { createInvalidCallBudget } = await import('@/agents/native/session/handle-invalid-tool-call');
  const registry = createLoopEventRegistry();
  const deps = { sessionName: 'acceptance-session', budget: createInvalidCallBudget(), onSpinStop: () => {}, loopHandlers: set, loopHandlerContext: context, ...overrides };
  registerBuiltinLoopHandlers(registry, deps);
  return { registry, deps, registerBuiltinLoopHandlers };
}
const tool = { name: 'name', description: 'fixture', inputSchema: { type: 'object', properties: { optional: { type: 'string' }, required: { type: 'string' } }, required: ['required'] } };
const valid = { call: { ...call, input: { required: 'ok' } }, tools: [tool] };

// The adapter fixture uses an in-process fake provider; no network service is needed.
async function nativeTurn(handlers: any[], responses: any[], options: Record<string, any> = {}) {
  const { NativeAgentAdapter } = await import('@/agents/native/adapter');
  const { _clientDeps, _resetNativeClient } = await import('@/agents/native/client');
  const dir = await mkdtemp(join(tmpdir(), 'nax-loop-accept-'));
  const requests: any[] = [];
  const old = _clientDeps.build;
  const model = { id: 'gpt-5.4-mini', provider: 'openai', protocol: 'openai-responses', pricing: { input: 3, output: 15, cacheRead: 0, cacheWrite: 0 }, contextWindow: 128000, supportsTools: true, thinkingLevels: [] };
  _clientDeps.build = async () => ({ model: async () => model, listModels: async () => [model], pricing: () => model.pricing, stream: async function* () {}, validate: () => {}, complete: async (_model: any, req: any) => { requests.push(req); return responses[Math.min(requests.length - 1, responses.length - 1)]; } }) as any;
  try {
    const adapter = new NativeAgentAdapter();
    const opts = { modelDef: { provider: 'unknown', model: 'openai/gpt-5.4-mini' }, workdir: dir, resolvedPermissions: { mode: 'approve-all', bashApproval: 'raw' }, loopHandlers: handlers, loopHandlerContext: context, ...options } as any;
    const handle = await adapter.openSession('loop-accept', { ...opts, transcriptDir: dir } as any);
    const result = await adapter.sendTurn(handle, 'hello', opts);
    return { requests, result, dir };
  } finally { _clientDeps.build = old; _resetNativeClient(); await rm(dir, { recursive: true, force: true }); }
}
const answer = { text: 'done', usage: { inputTokens: 10, outputTokens: 2 }, stopReason: 'stop' };

describe('plugin-loop-handlers acceptance', () => {
  test('AC-1: valid loop-handlers extension passes validation without warning', async () => { const l = await logs(); try { const { validatePlugin } = await import('@/plugins/validator'); const p = plugin('valid', mock(() => {})); expect(validatePlugin(p, p.name)).toBe(p); expect(l.matching('plugins', 'warn')).toHaveLength(0); } finally { l.dispose(); } });
  test('AC-2: missing loopHandlers is rejected with named warning', async () => { const l = await logs(); try { const { validatePlugin } = await import('@/plugins/validator'); expect(validatePlugin(plugin('missing', undefined), 'missing')).toBeNull(); expect(l.matching('plugins','warn')).toHaveLength(1); expect(l.matching('plugins','warn')[0].message).toMatch(/missing.*loopHandlers|loopHandlers.*missing/); } finally { l.dispose(); } });
  test('AC-3: non-function or missing register is rejected with named warning', async () => { const l = await logs(); try { const { validatePlugin } = await import('@/plugins/validator'); for (const [name, extension] of [['string', { register: 'not-a-function' }], ['empty', {}]] as const) { const p = { name, version: '1.0.0', provides: ['loop-handlers'], extensions: { loopHandlers: extension } }; expect(validatePlugin(p, name)).toBeNull(); const warning = l.matching('plugins','warn').at(-1); expect(warning.message).toContain(name); expect(warning.message).toContain('register'); } expect(l.matching('plugins','warn')).toHaveLength(2); } finally { l.dispose(); } });
  test('AC-4: empty or unrelated registry returns frozen empty set', async () => { const { PluginRegistry } = await import('@/plugins/registry'); for (const ps of [[], [{ name: 'other', version: '1', provides: ['reporter'], extensions: {} }]]) { const result = new PluginRegistry(ps as any).getLoopHandlers(); expect(result).toHaveLength(0); expect(Object.isFrozen(result)).toBe(true); } });
  test('AC-5: registry collects attributed entries preserving handler identity', async () => { const { PluginRegistry } = await import('@/plugins/registry'); const a = () => ({}), b = () => ({}); const result = new PluginRegistry([plugin('test-plugin', (on: any) => { on('after_tool', a); on('after_agent', b); })] as any).getLoopHandlers(); expect(result).toEqual([{ plugin: 'test-plugin', event: 'after_tool', handler: a }, { plugin: 'test-plugin', event: 'after_agent', handler: b }]); expect(result[0].handler).toBe(a); expect(result[1].handler).toBe(b); });
  test('AC-6: registry preserves plugin order then registration order', async () => { const { PluginRegistry } = await import('@/plugins/registry'); const hA1 = () => {}, hA2 = () => {}, hB1 = () => {}; const result = new PluginRegistry([plugin('a', (on: any) => { on('after_tool', hA1); on('after_agent', hA2); }), plugin('b', (on: any) => on('after_tool', hB1))] as any).getLoopHandlers(); expect(result.map(x => x.handler)).toEqual([hA1, hA2, hB1]); result.forEach((x, i) => expect(x.handler).toBe([hA1,hA2,hB1][i])); });
  test('AC-7: registry result is immutable', async () => { const { PluginRegistry } = await import('@/plugins/registry'); const set = new PluginRegistry([]).getLoopHandlers(); expect(Object.isFrozen(set)).toBe(true); expect(() => (set as any).push(entry('after_tool', () => {}))).toThrow(); });
  test('AC-8: registration runs once and cached array has stable identity', async () => { const { PluginRegistry } = await import('@/plugins/registry'); const register = mock((on: any) => on('after_tool', () => {})); const registry = new PluginRegistry([plugin('p', register)] as any); const first = registry.getLoopHandlers(), second = registry.getLoopHandlers(); expect(register).toHaveBeenCalledTimes(1); expect(first).toBe(second); });
  test('AC-9: throwing plugin is isolated and warned about', async () => { const l = await logs(); try { const { PluginRegistry } = await import('@/plugins/registry'); const good = () => {}; const result = new PluginRegistry([plugin('bad', () => { throw Error('broken'); }), plugin('good', (on: any) => on('after_tool', good))] as any).getLoopHandlers(); expect(result).toEqual([{ plugin: 'good', event: 'after_tool', handler: good }]); expect(l.matching('plugins','warn')).toHaveLength(1); expect(l.matching('plugins','warn')[0].message).toContain('bad'); } finally { l.dispose(); } });
  test('AC-10: invalid event rolls back entire plugin without affecting siblings', async () => { const l = await logs(); try { const { PluginRegistry } = await import('@/plugins/registry'); const good = () => {}; const result = new PluginRegistry([plugin('bad-event-plugin', (on: any) => { on('after_tool', () => {}); on('before_everything', () => {}); }), plugin('good', (on: any) => on('after_tool', good))] as any).getLoopHandlers(); expect(result).toEqual([{ plugin: 'good', event: 'after_tool', handler: good }]); expect(l.matching('plugins','warn')).toHaveLength(1); expect(l.matching('plugins','warn')[0].message).toContain('bad-event-plugin'); expect(l.matching('plugins','warn')[0].message).toContain('before_everything'); } finally { l.dispose(); } });
  test('AC-11: barrel exports context and external handler types compatible with registry set', async () => { const { PluginRegistry } = await import('@/plugins/registry'); type T = typeof import('@/agents/native/session/loop-events'); type LoopHandlerContext = import('@/agents/native/session/loop-events').LoopHandlerContext; type ExternalHandlerOf<E extends 'after_tool'> = import('@/agents/native/session/loop-events').ExternalHandlerOf<E>; type LoopHandlerEntry = import('@/agents/native/session/loop-events').LoopHandlerEntry; type LoopHandlerSet = import('@/agents/native/session/loop-events').LoopHandlerSet; type PayloadOf<E extends 'after_tool'> = import('@/agents/native/session/loop-events/types').PayloadOf<E>; const handler: ExternalHandlerOf<'after_tool'> = (_payload: PayloadOf<'after_tool'>, _ctx: LoopHandlerContext) => undefined; const e: LoopHandlerEntry = { plugin: 'p', event: 'after_tool', handler }; const set: LoopHandlerSet = new PluginRegistry([plugin('p', (on: any) => on('after_tool', handler))] as any).getLoopHandlers(); expect(set[0]).toEqual(e); });
  test('AC-12: external handler default timeout is ten seconds', async () => { const { LOOP_HANDLER_TIMEOUT_MS } = await import('@/agents/native/session/loop-events/external-handler'); expect(LOOP_HANDLER_TIMEOUT_MS).toBe(10000); });
  test('AC-13: wrapper passes payload and current context by reference exactly once', async () => { const payload = { ...after }; const sentinel = { unique: true }; const handler = mock(() => undefined); await (await external('after_tool', handler, 'p', new AbortController().signal, () => sentinel as any))(payload); expect(handler).toHaveBeenCalledTimes(1); expect(handler.mock.calls[0][0]).toEqual(payload); expect(handler.mock.calls[0][1]).toBe(sentinel); });
  test('AC-14: after_tool undefined result becomes empty patch', async () => { expect(await (await external('after_tool', () => undefined))(after)).toEqual({}); });
  test('AC-15: before_tool undefined allows while other events return empty patch', async () => { expect(await (await external('before_tool', () => undefined))(before)).toEqual({ kind: 'allow' }); expect(await (await external('after_tool', () => undefined))(after)).toEqual({}); });
  test('AC-16: before_tool block outcome is returned unchanged', async () => { const block = { kind: 'block', content: 'no', isError: true }; expect(await (await external('before_tool', () => block))(before)).toEqual(block); });
  test('AC-17: synchronous before_tool failure is converted into attributed block', async () => { const result = await (await external('before_tool', () => { throw Error('boom'); }))(before); failBlock(result); expect(result.content).toMatch(/^Blocked: loop handler from plugin 'p' failed \(/); });
  test('AC-18: rejected before_tool promise is converted into attributed block', async () => { failBlock(await (await external('before_tool', () => Promise.reject(Error('boom'))))(before)); });
  test('AC-19: timed-out before_tool handler fails closed promptly', async () => { await withTimeout(20, async () => { const start = Date.now(); failBlock(await (await external('before_tool', never))(before)); expect(Date.now() - start).toBeLessThan(1000); }); });
  test('AC-20: string before_tool verdict fails closed', async () => { failBlock(await (await external('before_tool', () => 'allow'))(before)); });
  test('AC-21: unknown before_tool kind fails closed', async () => { failBlock(await (await external('before_tool', () => ({ kind: 'maybe' })))(before)); });
  test('AC-22: failing before_tool warning attributes plugin event tool and error', async () => { const l = await logs(); try { await (await external('before_tool', () => { throw Error('boom'); }))(before); const warnings = l.matching('native-loop-events','warn'); expect(warnings).toHaveLength(1); expect(warnings[0].data).toMatchObject({ plugin: 'p', event: 'before_tool', tool: 'name' }); expect(warnings[0].data.error).toBeDefined(); } finally { l.dispose(); } });
  test('AC-23: after_tool failure warns once and fails open', async () => { const l = await logs(); try { expect(await (await external('after_tool', () => { throw Error('boom'); }))(after)).toEqual({}); expect(l.matching('native-loop-events','warn')).toHaveLength(1); expect(l.matching('native-loop-events','warn')[0].data).toMatchObject({ plugin: 'p', event: 'after_tool' }); } finally { l.dispose(); } });
  test('AC-24: before_turn_end timeout fails open and warns', async () => { const l = await logs(); try { await withTimeout(20, async () => { const start = Date.now(); expect(await (await external('before_turn_end', never))({ messages: [], roundTrips: 1, ended: 'completed', stopped: false, followUpsSoFar: 0 })).toEqual({}); expect(Date.now() - start).toBeLessThan(1000); }); expect(l.matching('native-loop-events','warn')).toHaveLength(1); expect(l.matching('native-loop-events','warn')[0].data).toMatchObject({ plugin: 'p', event: 'before_turn_end' }); } finally { l.dispose(); } });
  test('AC-25: abort ends pending handler before long timeout', async () => { await withTimeout(5000, async () => { const controller = new AbortController(); const wrapped = await external('before_tool', never, 'p', controller.signal); const pending = wrapped(before); const start = Date.now(); controller.abort(); failBlock(await pending); expect(Date.now() - start).toBeLessThan(500); }); });
  test('AC-26: late allow cannot overwrite timeout block', async () => { await withTimeout(20, async () => { const result = await (await external('before_tool', () => new Promise(resolve => setTimeout(() => resolve({ kind: 'allow' }), 50))))(before); failBlock(result); await new Promise(resolve => setTimeout(resolve, 70)); failBlock(result); }); });
  test('AC-27: promptly settled wrapper clears its timeout', async () => { const { _externalHandlerDeps, LOOP_HANDLER_TIMEOUT_MS } = await import('@/agents/native/session/loop-events/external-handler'); const old = _externalHandlerDeps.clearTimeout; const cleared = mock(old); _externalHandlerDeps.clearTimeout = cleared; try { const l = await logs(); try { const wrapped = await external('after_tool', () => ({ content: 'ok' })); expect(await wrapped(after)).toEqual({ content: 'ok' }); expect(cleared).toHaveBeenCalled(); const warnings = l.matching('native-loop-events','warn').length; await new Promise(resolve => setTimeout(resolve, 1)); expect(l.matching('native-loop-events','warn')).toHaveLength(warnings); expect(LOOP_HANDLER_TIMEOUT_MS).toBe(10000); } finally { l.dispose(); } } finally { _externalHandlerDeps.clearTimeout = old; } });
  test('AC-28: before_turn patch is preserved and debug log names fields', async () => { const l = await logs(); try { const message = { role: 'user', content: 'seed' }; const patch = { seed: [message] }; expect(await (await external('before_turn', () => patch))({ prompt: 'hi', history: [], sessionName: 's', boundary: true })).toEqual(patch); expect(l.matching('native-loop-events','debug')).toHaveLength(1); expect(l.matching('native-loop-events','debug')[0].data).toMatchObject({ plugin: 'p', event: 'before_turn', fields: ['seed'] }); } finally { l.dispose(); } });
  test('AC-29: dispatch of wrapped throwing before_tool logs only once', async () => { const l = await logs(); try { const { createLoopEventRegistry } = await import('@/agents/native/session/loop-events'); const registry = createLoopEventRegistry(); registry.register('before_tool', await external('before_tool', () => { throw Error('boom'); }) as any); failBlock(await registry.dispatch('before_tool', before)); expect(l.matching('native-loop-events','warn')).toHaveLength(1); } finally { l.dispose(); } });
  test('AC-30: dispatch of wrapped undefined before_tool warns once and allows', async () => { const l = await logs(); try { const { createLoopEventRegistry } = await import('@/agents/native/session/loop-events'); const registry = createLoopEventRegistry(); registry.register('before_tool', await external('before_tool', () => undefined) as any); expect(await registry.dispatch('before_tool', before)).toEqual({ kind: 'allow' }); expect(l.matching('native-loop-events','warn')).toHaveLength(1); } finally { l.dispose(); } });
  test('AC-31: builtin repairs null optional before plugin receives call', async () => { let received: any; const { registry } = await builtin([entry('before_tool', (payload: any) => { received = payload.call; return { kind: 'allow' }; })]); await registry.dispatch('before_tool', { ...valid, call: { ...valid.call, input: { required: 'ok', optional: null } } } as any); expect(received).toBeDefined(); expect(Object.hasOwn(received.input, 'optional')).toBe(false); });
  test('AC-32: builtin truncates plugin after_tool output', async () => { const { MODEL_MAX_BYTES } = await import('@/tools'); const { registry } = await builtin([entry('after_tool', () => ({ content: 'X'.repeat(MODEL_MAX_BYTES + 1000) }))]); const patch = await registry.dispatch('after_tool', after); expect(patch.content).toBeDefined(); expect(patch.content).not.toBe('X'.repeat(MODEL_MAX_BYTES + 1000)); expect(Buffer.byteLength(patch.content!)).toBeLessThanOrEqual(MODEL_MAX_BYTES); });
  test('AC-33: second plugin after_tool sees first plugin patch', async () => { let seen: any; const { registry } = await builtin([entry('after_tool', () => ({ content: 'C1' })), entry('after_tool', (payload: any) => { seen = payload.content; return {}; })]); await registry.dispatch('after_tool', after); expect(seen).toBe('C1'); });
  test('AC-34: invalid-call repair blocks before plugin is invoked', async () => { const handler = mock(() => ({ kind: 'allow' })); const { registry } = await builtin([entry('before_tool', handler)]); expect((await registry.dispatch('before_tool', { ...valid, call: { ...call, input: { required: 42 } } } as any)).kind).toBe('block'); expect(handler).toHaveBeenCalledTimes(0); });
  test('AC-35: spin breaker termination skips plugin', async () => { const handler = mock(() => ({ kind: 'allow' })); const { registry } = await builtin([entry('before_tool', handler)], { spinBreaker: { observe: () => ({ action: 'stop', reason: 'repeated' }) } }); expect((await registry.dispatch('before_tool', valid as any)).kind).toBe('terminate'); expect(handler).toHaveBeenCalledTimes(0); });
  test('AC-36: re-registering same registry does not duplicate plugin', async () => { const handler = mock(() => ({ kind: 'allow' })); const { registry, deps, registerBuiltinLoopHandlers } = await builtin([entry('before_tool', handler)]); registerBuiltinLoopHandlers(registry, { ...deps }); await registry.dispatch('before_tool', valid as any); expect(handler).toHaveBeenCalledTimes(1); });
  test('AC-37: re-registration repoints handler context', async () => { let received: any; const ctx1 = { sessionName: 'first' }, ctx2 = { sessionName: 'second' }; const { registry, deps, registerBuiltinLoopHandlers } = await builtin([entry('before_tool', (_: any, ctx: any) => { received = ctx; return { kind: 'allow' }; })], { loopHandlerContext: ctx1 }); registerBuiltinLoopHandlers(registry, { ...deps, loopHandlerContext: ctx2 }); await registry.dispatch('before_tool', valid as any); expect(received).toBe(ctx2); expect(received).not.toBe(ctx1); });
  test('AC-38: aborting pending plugin through builtins blocks with attribution', async () => { const controller = new AbortController(); const { registry } = await builtin([entry('before_tool', never, 'p')], { signal: controller.signal }); const pending = registry.dispatch('before_tool', valid as any); controller.abort(); failBlock(await pending); });
  test('AC-39: native adapter includes before_turn seed in first model request', async () => { const seed = { role: 'user', content: 'seed-marker' }; const { requests } = await nativeTurn([entry('before_turn', () => ({ seed: [seed] }))], [answer]); expect(JSON.stringify(requests[0].messages)).toContain('seed-marker'); });
  test('AC-40: before_tool block prevents Bash execution and records refused error result', async () => { const executed = mock(() => ({ content: 'executed' })); const response = { ...answer, toolCalls: [{ id: 'bash-1', name: 'Bash', input: { command: 'echo forbidden' } }], stopReason: 'tool_use' }; const { requests } = await nativeTurn([entry('before_tool', () => ({ kind: 'block', content: 'refused', isError: true }))], [response, answer], { tools: [{ name: 'Bash', description: 'shell', inputSchema: { type: 'object', properties: { command: { type: 'string' } } }, execute: executed }] }); expect(executed).toHaveBeenCalledTimes(0); expect(JSON.stringify(requests[1].messages)).toContain('refused'); expect(requests[1].messages.some((m: any) => m.role === 'tool-result' && m.content === 'refused' && m.isError === true)).toBe(true); });
  test('AC-41: throwing before_tool plugin produces named blocked tool result', async () => { const response = { ...answer, toolCalls: [{ id: 'bash-1', name: 'Bash', input: { command: 'echo x' } }], stopReason: 'tool_use' }; const { requests } = await nativeTurn([entry('before_tool', () => { throw Error('boom'); })], [response, answer]); const result = requests[1].messages.find((m: any) => m.role === 'tool-result'); expect(result.content).toMatch(/^Blocked: loop handler from plugin 'p' failed/); });
  test('AC-42: one before_turn_end followUp adds one request and one user message', async () => { let count = 0; const { requests } = await nativeTurn([entry('before_turn_end', () => ++count === 1 ? { followUp: 'one followup' } : {})], [answer, answer]); expect(requests).toHaveLength(2); expect(requests[1].messages.filter((m: any) => m.role === 'user' && JSON.stringify(m).includes('one followup'))).toHaveLength(1); });
  test('AC-43: all four adapter event handlers receive identical supplied context', async () => { const seen: any[] = []; const ctx = { sessionName: 'ctx-X', role: 'implementer' }; const response = { ...answer, toolCalls: [{ id: 'c1', name: 'Bash', input: { command: 'echo ok' } }], stopReason: 'tool_use' }; const handlers = ['before_turn','before_tool','after_tool','before_turn_end'].map(event => entry(event, (_: any, c: any) => { seen.push(c); return event === 'before_tool' ? { kind: 'block', content: 'blocked' } : {}; })); await nativeTurn(handlers, [response, answer], { loopHandlerContext: ctx }); expect(seen).toHaveLength(4); seen.forEach(c => expect(c).toBe(ctx)); });
  test('AC-44: empty set creates no native turn options', async () => { const { buildLoopHandlerTurnOpts } = await import('@/session/loop-handler-forwarding'); expect(buildLoopHandlerTurnOpts({ handle: { id: 's', agentName: 'native', role: 'implementer' } as any, descriptor: undefined, set: [] })).toEqual({}); });
  test('AC-45: non-native handle receives no handler options', async () => { const { buildLoopHandlerTurnOpts } = await import('@/session/loop-handler-forwarding'); expect(buildLoopHandlerTurnOpts({ handle: { id: 's', agentName: 'claude', role: 'implementer' } as any, descriptor: undefined, set: [entry('after_tool', () => ({}))] as any })).toEqual({}); });
  test('AC-46: native options preserve every set entry and its order', async () => { const { buildLoopHandlerTurnOpts } = await import('@/session/loop-handler-forwarding'); const { NATIVE_AGENT_NAME } = await import('@/config'); const set = [entry('after_tool', () => ({})), entry('before_tool', () => ({ kind: 'allow' }))]; const result = buildLoopHandlerTurnOpts({ handle: { id: 's', agentName: NATIVE_AGENT_NAME, role: 'implementer' } as any, descriptor: undefined, set: set as any }); expect(result.loopHandlers).toEqual(set); expect(result.loopHandlers?.map((e: any) => e.handler)).toEqual(set.map(e => e.handler)); });
  test('AC-47: native context derives descriptor and optional model fields', async () => { const { buildLoopHandlerTurnOpts } = await import('@/session/loop-handler-forwarding'); const { NATIVE_AGENT_NAME } = await import('@/config'); const descriptor = { role: 'implementer', storyId: 'S', featureName: 'F', workdir: '/tmp/W' }; const handle = { id: 's', agentName: NATIVE_AGENT_NAME, role: 'reviewer', modelDef: { model: 'M', provider: 'P' } }; const set = [entry('after_tool', () => ({}))] as any; expect(buildLoopHandlerTurnOpts({ handle: handle as any, descriptor: descriptor as any, set }).loopHandlerContext).toEqual({ sessionName: 's', role: 'implementer', storyId: 'S', feature: 'F', workdir: '/tmp/W', model: 'M', provider: 'P' }); const without = buildLoopHandlerTurnOpts({ handle: { ...handle, modelDef: undefined } as any, descriptor: descriptor as any, set }).loopHandlerContext!; expect(Object.hasOwn(without, 'model')).toBe(false); expect(Object.hasOwn(without, 'provider')).toBe(false); });
  test('AC-48: forwarded context is frozen', async () => { const { buildLoopHandlerTurnOpts } = await import('@/session/loop-handler-forwarding'); const { NATIVE_AGENT_NAME } = await import('@/config'); const ctx = buildLoopHandlerTurnOpts({ handle: { id: 's', agentName: NATIVE_AGENT_NAME, role: 'implementer' } as any, descriptor: undefined, set: [entry('after_tool', () => ({}))] as any }).loopHandlerContext; expect(Object.isFrozen(ctx)).toBe(true); });
  test('AC-49: context without descriptor falls back to handle role', async () => { const { buildLoopHandlerTurnOpts } = await import('@/session/loop-handler-forwarding'); const { NATIVE_AGENT_NAME } = await import('@/config'); const ctx = buildLoopHandlerTurnOpts({ handle: { id: 's', agentName: NATIVE_AGENT_NAME, role: 'implementer' } as any, descriptor: undefined, set: [entry('after_tool', () => ({}))] as any }).loopHandlerContext!; expect(ctx.role).toBe('implementer'); for (const key of ['storyId','feature','workdir']) expect((ctx as any)[key]).toBeUndefined(); });
  test('AC-50: configured manager forwards set and descriptor storyId', async () => { const { SessionManager } = await import('@/session/manager'); const set = [entry('after_tool', () => ({}))]; const sent = mock(async () => ({ output: 'ok', tokenUsage: { inputTokens: 1, outputTokens: 1 }, estimatedCostUsd: 0, internalRoundTrips: 1 })); const adapter = { name: 'native', openSession: async (id: string) => ({ id, agentName: 'native' }), sendTurn: sent }; const manager = new SessionManager({ getAdapter: () => adapter as any }); manager.configureLoopHandlers(set as any); const handle = await manager.openSession('accept', { agentName: 'native', workdir: '/tmp', pipelineStage: 'run', modelDef: { provider: 'P', model: 'M', env: {} }, timeoutSeconds: 30, storyId: 'S' } as any); await manager.sendPrompt(handle, 'hi'); expect(sent).toHaveBeenCalledTimes(1); expect(sent.mock.calls[0][2].loopHandlers).toEqual(set); expect(sent.mock.calls[0][2].loopHandlerContext.storyId).toBe('S'); });
  test('AC-51: unconfigured manager omits both loop option keys', async () => { const { SessionManager } = await import('@/session/manager'); const sent = mock(async () => ({ output: 'ok', tokenUsage: { inputTokens: 1, outputTokens: 1 }, estimatedCostUsd: 0, internalRoundTrips: 1 })); const manager = new SessionManager({ getAdapter: () => ({ name: 'native', openSession: async (id: string) => ({ id, agentName: 'native' }), sendTurn: sent }) as any }); const handle = await manager.openSession('accept', { agentName: 'native', workdir: '/tmp', pipelineStage: 'run', modelDef: { provider: 'P', model: 'M', env: {} }, timeoutSeconds: 30 } as any); await manager.sendPrompt(handle, 'hi'); expect(sent).toHaveBeenCalledTimes(1); expect(Object.hasOwn(sent.mock.calls[0][2], 'loopHandlers')).toBe(false); expect(Object.hasOwn(sent.mock.calls[0][2], 'loopHandlerContext')).toBe(false); });
  test('AC-52: non-native sessions log native-only notice exactly once', async () => { const l = await logs(); try { const { SessionManager } = await import('@/session/manager'); const manager = new SessionManager({ getAdapter: () => ({ name: 'claude', openSession: async (id: string) => ({ id, agentName: 'claude' }), sendTurn: async () => ({ output: 'ok', tokenUsage: { inputTokens: 1, outputTokens: 1 }, estimatedCostUsd: 0, internalRoundTrips: 1 }) }) as any }); manager.configureLoopHandlers([entry('after_tool', () => ({}))] as any); for (const id of ['first','second']) { const handle = await manager.openSession(id, { agentName: 'claude', workdir: '/tmp', pipelineStage: 'run', modelDef: { provider: 'P', model: 'M', env: {} }, timeoutSeconds: 30 } as any); await manager.sendPrompt(handle, 'hi'); } expect(l.records.filter(r => r.stage === 'plugins' && r.level === 'info' && r.message === 'loop handlers apply to the native agent only')).toHaveLength(1); } finally { l.dispose(); } });
  test('AC-53: initializeAfterLock configures one loaded loop handler set', async () => { const dir = await mkdtemp(join(tmpdir(), 'nax-plugin-init-')); try { const pluginsDir = join(dir, '.nax/plugins'); await mkdir(pluginsDir, { recursive: true }); await writeFile(join(pluginsDir, 'seed.ts'), `export default { name: 'seed', version: '1.0.0', provides: ['loop-handlers'], extensions: { loopHandlers: { register(on) { on('before_turn', () => ({ seed: [{ role: 'user', content: 'seed' }] })); } } } };`); const { initializeAfterLock } = await import('@/execution/lifecycle/run-setup-init'); const { DEFAULT_CONFIG } = await import('@/config'); const prd = { project: 'fixture', description: 'fixture', userStories: [] }; const prdPath = join(dir, 'prd.json'); await writeFile(prdPath, JSON.stringify(prd)); const runtime: any = { outputDir: join(dir, '.nax'), sessionManager: { configureLoopHandlers: mock(() => {}) }, agentManager: { getAgent: () => ({ name: 'native', isInstalled: async () => true }) } }; await initializeAfterLock({ config: structuredClone(DEFAULT_CONFIG), workdir: dir, feature: 'fixture', dryRun: true, runtime, prdPath, prd: prd as any, interactionChain: null, runId: 'acceptance', agentGetFn: () => ({ name: 'native', isInstalled: async () => true }) as any, statusWriter: { setPrd: () => {} } as any, deps: { detectProjectProfile: async () => ({}), sweepFeatureTranscripts: async () => 0 } as any }); expect(runtime.sessionManager.configureLoopHandlers).toHaveBeenCalledTimes(1); expect(runtime.sessionManager.configureLoopHandlers.mock.calls[0][0]).toHaveLength(1); expect(runtime.sessionManager.configureLoopHandlers.mock.calls[0][0][0].plugin).toBe('seed'); } finally { await rm(dir, { recursive: true, force: true }); } });
  test('AC-54: loaded plugin seed travels through manager into native model request', async () => { const dir = await mkdtemp(join(tmpdir(), 'nax-plugin-e2e-')); try { const pluginsDir = join(dir, '.nax/plugins'); await mkdir(pluginsDir, { recursive: true }); await writeFile(join(pluginsDir, 'seed.ts'), `export default { name: 'seed', version: '1.0.0', provides: ['loop-handlers'], extensions: { loopHandlers: { register(on) { on('before_turn', () => ({ seed: [{ role: 'user', content: 'loaded-seed-marker' }] })); } } } };`); const { loadPlugins } = await import('@/plugins/loader'); const registry = await loadPlugins(join(dir, 'absent-global'), pluginsDir, [], dir); const set = registry.getLoopHandlers(); expect(set).toHaveLength(1); const { SessionManager } = await import('@/session/manager'); const { NativeAgentAdapter } = await import('@/agents/native/adapter'); const { _clientDeps, _resetNativeClient } = await import('@/agents/native/client'); const old = _clientDeps.build; const requests: any[] = []; const model = { id: 'gpt-5.4-mini', provider: 'openai', protocol: 'openai-responses', pricing: { input: 3, output: 15, cacheRead: 0, cacheWrite: 0 }, contextWindow: 128000, supportsTools: true, thinkingLevels: [] }; _clientDeps.build = async () => ({ model: async () => model, listModels: async () => [model], pricing: () => model.pricing, stream: async function* () {}, validate: () => {}, complete: async (_: any, req: any) => { requests.push(req); return answer; } }) as any; try { const manager = new SessionManager({ getAdapter: () => new NativeAgentAdapter() }); manager.configureLoopHandlers(set); const handle = await manager.openSession('seed-session', { agentName: 'native', workdir: dir, pipelineStage: 'run', modelDef: { provider: 'unknown', model: 'openai/gpt-5.4-mini', env: {} }, timeoutSeconds: 30 } as any); await manager.sendPrompt(handle, 'hello'); expect(requests).toHaveLength(1); expect(JSON.stringify(requests[0].messages)).toContain('loaded-seed-marker'); } finally { _clientDeps.build = old; _resetNativeClient(); } } finally { await rm(dir, { recursive: true, force: true }); } });
  test('AC-55: adapter boundary script rejects plugin import and identifies file', async () => { const dir = await mkdtemp(join(tmpdir(), 'nax-adapter-check-')); try { await mkdir(join(dir, 'src/agents/native'), { recursive: true }); await writeFile(join(dir, 'src/agents/native/x.ts'), `import { PluginRegistry } from '@/plugins';\n`); const result = spawnSync('bash', [join(root, 'scripts/check-adapter-no-config-import.sh')], { cwd: dir, encoding: 'utf8' }); expect(result.status).toBe(1); expect(result.stdout + result.stderr).toContain('x.ts'); } finally { await rm(dir, { recursive: true, force: true }); } });
  test('AC-56: adapter boundary script permits loop-events import', async () => { const dir = await mkdtemp(join(tmpdir(), 'nax-adapter-check-')); try { await mkdir(join(dir, 'src/agents/native'), { recursive: true }); await writeFile(join(dir, 'src/agents/native/x.ts'), `import { createLoopEventRegistry } from '@/agents/native/session/loop-events';\n`); const result = spawnSync('bash', [join(root, 'scripts/check-adapter-no-config-import.sh')], { cwd: dir, encoding: 'utf8' }); expect(result.status).toBe(0); expect(result.stdout + result.stderr).not.toContain('x.ts'); } finally { await rm(dir, { recursive: true, force: true }); } });
});