import { describe, expect, test } from "bun:test";
import { readFile, readdir } from "node:fs/promises";
import { join } from "node:path";
import { makeMockCallContext, opSelector, withTempDir } from "@test/helpers";
import { buildCompleteEvent, buildDispatchErrorEvent } from "@/agents/manager-dispatch";
import { CostAggregator } from "@/runtime/cost-aggregator";
import { DispatchEventBus, type DispatchErrorEvent, type SessionTurnDispatchEvent } from "@/runtime/dispatch-events";
import { attachReviewAuditSubscriber } from "@/runtime/middleware/review-audit";
import { COST_ROW_SCHEMA_VERSION, attachCostSubscriber } from "@/runtime/middleware/cost";
import { ReviewAuditor } from "@/review/review-audit";
import { emitReviewDecision, toReviewDecisionPayload } from "@/execution/story-orchestrator/review-decision";
import { adversarialReviewOp, type AdversarialReviewInput, type AdversarialReviewOutput } from "@/operations/adversarial-review";

const permissions = { mode: "approve-reads" as const };

function sessionEvent(overrides: Record<string, unknown> = {}): SessionTurnDispatchEvent {
  return {
    kind: "session-turn", sessionName: "ledger-session", sessionRole: "implementer", prompt: "prompt", response: "response",
    agentName: "native", model: "test-model", stage: "run", resolvedPermissions: permissions, durationMs: 1, timestamp: 1000,
    tokenUsage: { inputTokens: 10, outputTokens: 5 }, estimatedCostUsd: 0.01, exactCostUsd: 0.01,
    roundTrips: 1, roundTripUnit: "model-call", protocolIds: {}, origin: "runAsSession", ...overrides,
  } as unknown as SessionTurnDispatchEvent;
}
function errorEvent(overrides: Record<string, unknown> = {}): DispatchErrorEvent {
  return { kind: "error", origin: "runAsSession", agentName: "native", stage: "run", errorCode: "DISPATCH_ERROR", errorMessage: "failed", durationMs: 1, timestamp: 1000, resolvedPermissions: permissions, ...overrides } as DispatchErrorEvent;
}
async function persistedCostRow(event: SessionTurnDispatchEvent | DispatchErrorEvent): Promise<Record<string, unknown>[]> {
  return withTempDir(async (dir) => {
    const runId = "ledger-run", bus = new DispatchEventBus(), aggregator = new CostAggregator(runId, join(dir, "cost"));
    attachCostSubscriber(bus, aggregator, runId);
    if (event.kind === "error") bus.emitDispatchError(event); else bus.emitDispatch(event);
    await aggregator.drain();
    return (await readFile(join(dir, "cost", `${runId}.jsonl`), "utf8")).trim().split("\n").filter(Boolean).map((line) => JSON.parse(line) as Record<string, unknown>);
  });
}
async function persistedReview(output: unknown): Promise<Record<string, unknown>> {
  return withTempDir(async (dir) => {
    const ctx = makeMockCallContext({ packageDir: dir, featureName: "ledger-truth" });
    const auditor = new ReviewAuditor("audit-run", dir), off = attachReviewAuditSubscriber(ctx.runtime.dispatchEvents, auditor, "audit-run");
    emitReviewDecision(ctx, "adversarial-review", output); await auditor.flush(); off(); await ctx.runtime.close();
    const files = await readdir(join(dir, "review-audit", "ledger-truth")); expect(files).toHaveLength(1);
    return JSON.parse(await readFile(join(dir, "review-audit", "ledger-truth", files[0]), "utf8")) as Record<string, unknown>;
  });
}
const reviewBase = { passed: true, findings: [], normalizedFindings: [], acDropped: [] };

describe("ledger-and-audit-field-truth", () => {
  test("AC-1: Emit a CostEvent on the dispatch bus with roundTrips=7 and roundTripUnit=\"model-call\"; after attachCostSubscriber processes it and CostAggregator.drain() returns, the persisted schema-v4 cost row for that (runId, agentName, stage) has a defined roundTrips property with numeric value 7.", async () => { const [row] = await persistedCostRow(sessionEvent({ roundTrips: 7, roundTripUnit: "model-call" })); expect(row.roundTrips).toBe(7); });
  test("AC-2: Emit the same session-turn CostEvent with roundTrips=7 and roundTripUnit=\"model-call\"; the persisted cost row has roundTripUnit strictly equal to the string \"model-call\" (not \"agent-run\" and not undefined).", async () => { const [row] = await persistedCostRow(sessionEvent({ roundTrips: 7, roundTripUnit: "model-call" })); expect(row.roundTripUnit).toBe("model-call"); });
  test("AC-3: Emit a session-turn CostEvent with roundTrips=3 and roundTripUnit=\"agent-run\"; the persisted cost row has roundTrips === 3 and roundTripUnit === \"agent-run\", preserving the ACP delegated-agent-run unit unchanged.", async () => { const [row] = await persistedCostRow(sessionEvent({ roundTrips: 3, roundTripUnit: "agent-run" })); expect(row.roundTrips).toBe(3); expect(row.roundTripUnit).toBe("agent-run"); });
  test("AC-4: Emit a successful session-turn CostEvent whose source dispatch event carries no roundTrips/roundTripUnit values; the persisted cost row satisfies !('roundTrips' in row) and !('roundTripUnit' in row) — neither key is present, and neither is defaulted to 1.", async () => { const event = sessionEvent(); delete (event as unknown as Record<string, unknown>).roundTrips; delete (event as unknown as Record<string, unknown>).roundTripUnit; const [row] = await persistedCostRow(event); expect("roundTrips" in row).toBe(false); expect("roundTripUnit" in row).toBe(false); });
  test("AC-5: Call buildDispatchErrorEvent for a dispatch whose modelAttribution() returns a non-undefined model string M; assert that the returned DispatchErrorEvent.model === M (deep-equal to the modelAttribution() output for the same dispatch inputs).", () => { const modelDef = { model: "anthropic/claude-sonnet-5" }; const complete = buildCompleteEvent({ sessionName: "s", prompt: "p", response: "r", agentName: "native", stage: "run", options: { modelDef }, resolvedPermissions: permissions, tokenUsage: undefined, startedAt: Date.now() } as Parameters<typeof buildCompleteEvent>[0]); const error = buildDispatchErrorEvent({ origin: "runAsSession", agentName: "native", stage: "run", error: new Error("x"), resolvedPermissions: permissions, startedAt: Date.now(), modelDef } as unknown as Parameters<typeof buildDispatchErrorEvent>[0]); expect((error as unknown as Record<string, unknown>).model).toEqual(complete.model); });
  test("AC-6: Emit a DispatchErrorEvent with model=\"anthropic/claude-sonnet-5\" through the error path; after draining the aggregator, the persisted schema-v4 error cost row has model === \"anthropic/claude-sonnet-5\".", async () => { const [row] = await persistedCostRow(errorEvent({ model: "anthropic/claude-sonnet-5" })); expect(row.model).toBe("anthropic/claude-sonnet-5"); });
  test("AC-7: Emit a DispatchErrorEvent where model is undefined (modelAttribution() resolved nothing); the persisted error cost row satisfies !('model' in row) — the key is absent, and its value is never the string \"unknown\".", async () => { const [row] = await persistedCostRow(errorEvent()); expect("model" in row).toBe(false); expect(row.model).not.toBe("unknown"); });
  test("AC-8: Emit a successful session-turn CostEvent with tokenUsage === undefined and exactCostUsd === 0 (and estimatedCostUsd === 0); after CostAggregator.drain(), the drain result contains exactly 1 cost row for that runId — the usage-less success is not dropped and not duplicated.", async () => { expect(await persistedCostRow(sessionEvent({ tokenUsage: undefined, exactCostUsd: 0, estimatedCostUsd: 0 }))).toHaveLength(1); });
  test("AC-9: Emit the usage-less successful session-turn CostEvent (tokenUsage undefined, exactCostUsd 0); the persisted cost row has usageMissing === true (boolean true, not undefined/null).", async () => { const [row] = await persistedCostRow(sessionEvent({ tokenUsage: undefined, exactCostUsd: 0, estimatedCostUsd: 0 })); expect(row.usageMissing).toBe(true); });
  test("AC-10: Emit the usage-less successful session-turn CostEvent (tokenUsage undefined); the persisted cost row satisfies !('tokens' in row) — the tokens key is absent entirely, and the row does not contain a zeroed tokens object {input: 0, output: 0}.", async () => { const [row] = await persistedCostRow(sessionEvent({ tokenUsage: undefined, exactCostUsd: 0, estimatedCostUsd: 0 })); expect("tokens" in row).toBe(false); });
  test("AC-11: Emit a successful session-turn CostEvent with a defined tokenUsage object (e.g. {input: 100, output: 50}); the persisted cost row satisfies !('usageMissing' in row) — the usageMissing key is absent, not set to false.", async () => { const [row] = await persistedCostRow(sessionEvent({ tokenUsage: { inputTokens: 100, outputTokens: 50 } })); expect("usageMissing" in row).toBe(false); });
  test("AC-12: Emit any successful session-turn CostEvent; after it is persisted, the cost row has schemaVersion === 4 (matching COST_ROW_SCHEMA_VERSION exported from src/runtime/middleware/cost.ts), and the doc comment above that constant documents the v4 guarantees (roundTrips/roundTripUnit/usageMissing, optional tokens).", async () => { const [row] = await persistedCostRow(sessionEvent()); expect(COST_ROW_SCHEMA_VERSION).toBe(4); expect(row.schemaVersion).toBe(COST_ROW_SCHEMA_VERSION); const source = await readFile(join(import.meta.dir, "../../../src/runtime/middleware/cost.ts"), "utf8"); expect(source).toMatch(/4[\s\S]*roundTrips[\s\S]*roundTripUnit[\s\S]*usageMissing[\s\S]*tokens/i); });
  test("AC-13: Emit a DispatchErrorEvent through the error path; after it is persisted, the error cost row has schemaVersion === 4, identical to the schemaVersion stamped on success-path cost rows.", async () => { const [success] = await persistedCostRow(sessionEvent()), [failure] = await persistedCostRow(errorEvent()); expect(failure.schemaVersion).toBe(4); expect(failure.schemaVersion).toBe(success.schemaVersion); });
  test("AC-14: Calling toReviewDecisionPayload with an AdversarialReviewOutput object where modelPassed === true returns a ReviewDecisionPayload with a `modelPassed` property strictly equal to boolean true (Object.is(result.modelPassed, true)).", () => { const result = toReviewDecisionPayload("adversarial-review", { ...reviewBase, modelPassed: true }) as unknown as Record<string, unknown>; expect(Object.is(result.modelPassed, true)).toBe(true); });
  test("AC-15: Calling toReviewDecisionPayload with an AdversarialReviewOutput object where modelPassed === false returns a ReviewDecisionPayload where the `modelPassed` key is present (Object.prototype.hasOwnProperty.call(result, 'modelPassed') === true) and its value is strictly boolean false (Object.is(result.modelPassed, false)); the field must not be omitted or coerced.", () => { const result = toReviewDecisionPayload("adversarial-review", { ...reviewBase, modelPassed: false }) as unknown as Record<string, unknown>; expect(Object.prototype.hasOwnProperty.call(result, "modelPassed")).toBe(true); expect(Object.is(result.modelPassed, false)).toBe(true); });
  test("AC-16: Calling toReviewDecisionPayload with an op output object lacking a `modelPassed` property (e.g., a semantic review output) returns a payload where the `modelPassed` key is absent: Object.prototype.hasOwnProperty.call(result, 'modelPassed') === false and result.modelPassed === undefined.", () => { const result = toReviewDecisionPayload("semantic-review", reviewBase) as unknown as Record<string, unknown>; expect(Object.prototype.hasOwnProperty.call(result, "modelPassed")).toBe(false); expect(result.modelPassed).toBeUndefined(); });
  test("AC-17: Calling toReviewDecisionPayload with an op output whose `modelPassed` is the string \"yes\" (non-boolean value) returns a payload where the `modelPassed` key is absent: Object.prototype.hasOwnProperty.call(result, 'modelPassed') === false. The string value must not be truthiness-coerced into a boolean.", () => { const result = toReviewDecisionPayload("adversarial-review", { ...reviewBase, modelPassed: "yes" }) as unknown as Record<string, unknown>; expect(Object.prototype.hasOwnProperty.call(result, "modelPassed")).toBe(false); });
  test("AC-18: Integration/canary test (extending test/unit/execution/story-orchestrator/review-decision-field-forwarding.test.ts): invoking the real adversarialReviewOp.verify() on model output that claims a pass, passing its returned output through emitReviewDecision, and capturing the emitted 'review-decision' event yields a ReviewDecisionEvent with `modelPassed` present (hasOwnProperty true) and strictly equal to the boolean true returned by verify().", async () => { const ctx = makeMockCallContext(); let emitted: Record<string, unknown> | undefined; ctx.runtime.dispatchEvents.onReviewDecision((event) => { emitted = event as unknown as Record<string, unknown>; }); const input: AdversarialReviewInput = { workdir: "/tmp", story: { id: "AC-18", title: "t", description: "d", acceptanceCriteria: [] }, adversarialConfig: { model: "balanced", diffMode: "ref", rules: [], timeoutMs: 1, parallel: false, maxConcurrentSessions: 1, substantiation: { requote: true, maxRequotes: 1 } }, mode: "ref", blockingThreshold: "warning" }; const verify = adversarialReviewOp.verify!; const output = await verify({ ...reviewBase, modelPassed: true } as AdversarialReviewOutput, input, { packageView: ctx.packageView, config: ctx.packageView.select(opSelector(adversarialReviewOp.config)), readFile: async () => null, fileExists: async () => false }); emitReviewDecision(ctx, "adversarial-review", output); await ctx.runtime.close(); expect(emitted).toBeDefined(); expect(Object.prototype.hasOwnProperty.call(emitted, "modelPassed")).toBe(true); expect(emitted?.modelPassed).toBe(true); });
  test("AC-19: End-to-end test: calling emitReviewDecision with an adversarial op output where modelPassed === false results in the persisted review audit record (written by the audit subscriber/writer) having a `modelPassed` property present (hasOwnProperty true) whose value is strictly boolean false; the false value must be persisted, not dropped.", async () => { const row = await persistedReview({ ...reviewBase, modelPassed: false }); expect(Object.prototype.hasOwnProperty.call(row, "modelPassed")).toBe(true); expect(row.modelPassed).toBe(false); });
  test("AC-20: End-to-end test: calling emitReviewDecision with an op output where parsed === false, passed is fail-open-derived, and modelPassed === true results in the persisted review audit record containing modelPassed strictly equal to true; the read must occur outside the parsed branch, mirroring the existing blockingThreshold forwarding code path (persisted even when parsing failed).", async () => { const row = await persistedReview({ failOpen: true, modelPassed: true }); expect(row.parsed).toBe(false); expect(row.modelPassed).toBe(true); });
});