/**
 * `nax rules` CLI Commands (Phase 5.1)
 *
 * Provides commands for managing the canonical rules store (.nax/rules/):
 *
 *   nax rules export --agent=<id>
 *     One-way generation of per-agent shim files (CLAUDE.md, AGENTS.md,
 *     GEMINI.md) from the canonical store. Generation is canonical → shim only;
 *     manual edits to shims are not read back by the engine.
 *
 *   nax rules migrate
 *     Reads CLAUDE.md + .claude/rules/*.md and writes a .nax/rules/ draft
 *     with basic neutralization applied (removes Claude-specific phrasing).
 *     The operator reviews the diff before committing. Existing .nax/rules/
 *     files are preserved unless --force is passed.
 *
 *   nax rules lint
 *     Validates neutrality/frontmatter for canonical rules in the repo root
 *     and any package overlays.
 *
 * See: docs/specs/SPEC-context-engine-v2.md §Canonical rules delivery
 */

import { mkdir } from "node:fs/promises";
import { basename, join } from "node:path";
import { CANONICAL_RULES_DIR, loadCanonicalRules } from "../context/rules/canonical-loader";
import { NaxError } from "../errors";
import { errorMessage } from "../utils/errors";

// ─────────────────────────────────────────────────────────────────────────────
// Injectable deps
// ─────────────────────────────────────────────────────────────────────────────

export const _rulesCLIDeps = {
  readFile: async (path: string): Promise<string> => Bun.file(path).text(),
  writeFile: async (path: string, content: string): Promise<void> => {
    await Bun.write(path, content);
  },
  fileExists: async (path: string): Promise<boolean> => Bun.file(path).exists(),
  globInDir: (dir: string): string[] => {
    try {
      return [...new Bun.Glob("*.md").scanSync({ cwd: dir })].sort().map((f) => join(dir, f));
    } catch {
      return [];
    }
  },
  mkdir: async (path: string): Promise<void> => {
    await mkdir(path, { recursive: true });
  },
  globCanonicalRuleFiles: (workdir: string): string[] => {
    try {
      return [...new Bun.Glob("**/.nax/rules/**/*.md").scanSync({ cwd: workdir, absolute: false })].sort();
    } catch {
      return [];
    }
  },
  loadCanonicalRules,
};

// ─────────────────────────────────────────────────────────────────────────────
// Agent → shim file mapping
// ─────────────────────────────────────────────────────────────────────────────

const AGENT_SHIM_FILES: Record<string, string> = {
  claude: "CLAUDE.md",
  codex: "AGENTS.md",
  gemini: "GEMINI.md",
  cursor: ".cursorrules",
};

const SUPPORTED_AGENTS = Object.keys(AGENT_SHIM_FILES);

// ─────────────────────────────────────────────────────────────────────────────
// nax rules export
// ─────────────────────────────────────────────────────────────────────────────

export interface RulesExportOptions {
  /** Project working directory (default: process.cwd()) */
  dir?: string;
  /** Target agent: claude, codex, gemini, cursor */
  agent: string;
  /** Preview output without writing any files */
  dryRun?: boolean;
}

/**
 * `nax rules export --agent=<id>`
 *
 * Reads the canonical rules store (.nax/rules/*.md) and generates a
 * per-agent shim file at the project root. This is one-way — manual
 * edits to the shim are never read back by the engine.
 *
 * Throws NaxError when canonical store is empty or agent is unsupported.
 */
export async function rulesExportCommand(options: RulesExportOptions): Promise<void> {
  const workdir = options.dir ?? process.cwd();
  const agent = options.agent.toLowerCase();

  const shimFileName = AGENT_SHIM_FILES[agent];
  if (!shimFileName) {
    throw new NaxError(
      `Unsupported agent "${agent}". Supported: ${SUPPORTED_AGENTS.join(", ")}`,
      "RULES_EXPORT_UNSUPPORTED_AGENT",
      { stage: "rules-export", agent },
    );
  }

  const rules = await _rulesCLIDeps.loadCanonicalRules(workdir);
  if (rules.length === 0) {
    throw new NaxError(
      `No canonical rules found in ${CANONICAL_RULES_DIR}. Run \`nax rules migrate\` first.`,
      "RULES_EXPORT_NO_CANONICAL_RULES",
      { stage: "rules-export", workdir },
    );
  }

  const header = `<!-- AUTO-GENERATED by nax rules export --agent=${agent} -->
<!-- Do not edit manually — re-run this command to regenerate. -->
<!-- Source of truth: ${CANONICAL_RULES_DIR}/ -->

`;
  const body = rules.map((r) => `## ${r.fileName}\n\n${r.content}`).join("\n\n---\n\n");
  const shimContent = `${header + body}\n`;
  const shimPath = join(workdir, shimFileName);

  if (options.dryRun) {
    console.log(`[dry-run] Would write ${shimPath} (${shimContent.length} bytes)`);
    return;
  }

  await _rulesCLIDeps.writeFile(shimPath, shimContent);
  console.log(`[OK] Wrote ${shimFileName} (${rules.length} rule file(s) from ${CANONICAL_RULES_DIR}/)`);
}

// ─────────────────────────────────────────────────────────────────────────────
// Neutralization helpers (used by migrate)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Apply basic neutralization to source content:
 *   - Remove <system-reminder> tags
 *   - Replace "the <Word> tool" → "the <capability>"
 *   - Replace CLAUDE.md references → "project conventions"
 *   - Replace .claude/ directory references → ".nax/rules/"
 *   - Replace IMPORTANT: → "Note:"
 *   - Strip emoji characters
 *
 * Returns the neutralized content and a count of replacements made.
 */
export function neutralizeContent(content: string): { content: string; replacements: number } {
  let result = content;
  let replacements = 0;

  const apply = (pattern: RegExp, replacement: string): void => {
    const matches = [...result.matchAll(pattern)].length;
    if (matches > 0) {
      result = result.replace(pattern, replacement);
      replacements += matches;
    }
  };

  apply(/<system-reminder>[\s\S]*?<\/system-reminder>/gi, "");
  apply(/<system-reminder>/gi, "");
  apply(/\bthe ([A-Z][a-zA-Z]+) tool\b/g, "the $1 capability");
  apply(/CLAUDE\.md/g, "project conventions file");
  apply(/\.claude\//g, ".nax/rules/");
  apply(/\bIMPORTANT:/g, "Note:");
  apply(/\p{Extended_Pictographic}/gu, "");

  return { content: result.trim(), replacements };
}

// ─────────────────────────────────────────────────────────────────────────────
// nax rules migrate
// ─────────────────────────────────────────────────────────────────────────────

export interface RulesMigrateOptions {
  /** Project working directory (default: process.cwd()) */
  dir?: string;
  /** Overwrite existing .nax/rules/ files (default: false) */
  force?: boolean;
  /** Preview output without writing any files */
  dryRun?: boolean;
}

export interface RulesLintOptions {
  /** Project working directory (default: process.cwd()) */
  dir?: string;
}

interface MigrateSource {
  sourcePath: string;
  targetFileName: string;
  content: string;
}

/**
 * Collect source files to migrate: CLAUDE.md + .claude/rules/*.md
 */
async function collectMigrationSources(workdir: string): Promise<MigrateSource[]> {
  const sources: MigrateSource[] = [];

  // CLAUDE.md at root
  const claudeMdPath = join(workdir, "CLAUDE.md");
  if (await _rulesCLIDeps.fileExists(claudeMdPath)) {
    const content = await _rulesCLIDeps.readFile(claudeMdPath);
    if (content.trim()) {
      sources.push({ sourcePath: claudeMdPath, targetFileName: "project-conventions.md", content });
    }
  }

  // .claude/rules/*.md
  const rulesDir = join(workdir, ".claude", "rules");
  const ruleFiles = _rulesCLIDeps.globInDir(rulesDir);
  for (const filePath of ruleFiles) {
    try {
      const content = await _rulesCLIDeps.readFile(filePath);
      if (content.trim()) {
        sources.push({ sourcePath: filePath, targetFileName: basename(filePath), content });
      }
    } catch {
      // skip unreadable files
    }
  }

  return sources;
}

/**
 * `nax rules migrate`
 *
 * Reads CLAUDE.md + .claude/rules/*.md from the project and writes a
 * .nax/rules/ draft with basic neutralization applied. The operator
 * reviews the result before committing.
 *
 * Existing .nax/rules/ files are not overwritten unless --force is passed.
 */
export async function rulesMigrateCommand(options: RulesMigrateOptions): Promise<void> {
  const workdir = options.dir ?? process.cwd();
  const force = options.force ?? false;

  const sources = await collectMigrationSources(workdir);
  if (sources.length === 0) {
    console.log("[WARN] No source files found (checked CLAUDE.md and .claude/rules/*.md). Nothing to migrate.");
    return;
  }

  const targetDir = join(workdir, CANONICAL_RULES_DIR);

  if (!options.dryRun) {
    try {
      await _rulesCLIDeps.mkdir(targetDir);
    } catch (err) {
      throw new NaxError(
        `Failed to create ${CANONICAL_RULES_DIR}: ${errorMessage(err)}`,
        "RULES_MIGRATE_MKDIR_FAILED",
        { stage: "rules-migrate", targetDir },
      );
    }
  }

  let written = 0;
  let skipped = 0;

  for (const { sourcePath, targetFileName, content } of sources) {
    const targetPath = join(targetDir, targetFileName);

    if (!force && !options.dryRun && (await _rulesCLIDeps.fileExists(targetPath))) {
      console.log(`[skip] ${targetFileName} already exists (use --force to overwrite)`);
      skipped++;
      continue;
    }

    const { content: neutralized, replacements } = neutralizeContent(content);
    const notice =
      replacements > 0 ? `<!-- NOTE: ${replacements} neutralization(s) applied — review before committing -->\n\n` : "";
    const output = notice + neutralized;

    if (options.dryRun) {
      console.log(`[dry-run] Would write ${targetFileName} from ${sourcePath} (${replacements} replacements)`);
    } else {
      await _rulesCLIDeps.writeFile(targetPath, output);
      console.log(
        `[OK] ${targetFileName} <- ${sourcePath}${replacements > 0 ? ` (${replacements} replacements)` : ""}`,
      );
    }
    written++;
  }

  if (!options.dryRun) {
    console.log(`\nMigration complete: ${written} file(s) written, ${skipped} skipped.`);
    if (written > 0) {
      console.log(
        `Review ${CANONICAL_RULES_DIR}/ before committing. Run \`nax rules export --agent=claude\` to regenerate CLAUDE.md.`,
      );
    }
  }
}

function collectCanonicalRuleRoots(workdir: string): string[] {
  const roots = new Set<string>([workdir]);
  const files = _rulesCLIDeps.globCanonicalRuleFiles(workdir);
  for (const rel of files) {
    const normalized = rel.replaceAll("\\", "/");
    const marker = "/.nax/rules/";
    const idx = normalized.indexOf(marker);
    if (idx <= 0) continue; // root rules stay mapped to workdir
    const packageRel = normalized.slice(0, idx);
    if (!packageRel) continue;
    roots.add(join(workdir, packageRel));
  }
  return [...roots].sort();
}

/**
 * `nax rules lint`
 *
 * Validates canonical rules neutrality/frontmatter for the repository root
 * and any package-local `.nax/rules/` stores found under the workdir.
 */
export async function rulesLintCommand(options: RulesLintOptions): Promise<void> {
  const workdir = options.dir ?? process.cwd();
  const roots = collectCanonicalRuleRoots(workdir);

  let totalRuleFiles = 0;
  for (const root of roots) {
    const rules = await _rulesCLIDeps.loadCanonicalRules(root);
    totalRuleFiles += rules.length;
  }

  const scopeLabel = roots.length === 1 ? "repo root" : `${roots.length} rule roots`;
  console.log(`[OK] Canonical rules lint passed (${totalRuleFiles} file(s) across ${scopeLabel}).`);
}
