import { afterEach, expect, mock, test } from 'bun:test';
import { existsSync } from 'node:fs';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';

const roots: string[] = [];
const restores: Array<() => void> = [];
async function temporary() { const dir = await mkdtemp(path.join(tmpdir(), 'nax-hygiene-')); roots.push(dir); return dir; }
async function put(root: string, name: string, contents = '{}') { const target = path.join(root, name); await mkdir(path.dirname(target), { recursive: true }); await writeFile(target, contents); return target; }
function git(dir: string, ...args: string[]) {
  const p = Bun.spawnSync(['git', ...args], { cwd: dir, env: { ...process.env, GIT_AUTHOR_NAME: 'Test', GIT_AUTHOR_EMAIL: 'test@example.org', GIT_COMMITTER_NAME: 'Test', GIT_COMMITTER_EMAIL: 'test@example.org' } });
  if (p.exitCode !== 0) throw new Error(new TextDecoder().decode(p.stderr));
  return new TextDecoder().decode(p.stdout);
}
async function repo() { const dir = await temporary(); git(dir, 'init', '-q'); return dir; }
const M = '.nax/features/old/stories/US-001/context-manifest-a.json';
const R = '.nax/runs/r.json';
async function mixed() { const dir = await repo(); const outputDir = path.join(dir, 'output'); await put(dir, '.nax/config.json', JSON.stringify({ name: 'hygiene', outputDir })); await put(dir, M); git(dir, 'add', M); git(dir, 'commit', '-qm', 'manifest'); await put(dir, R); return { dir, outputDir }; }
async function capture() {
  const { resetLogger, initLogger, addSink } = await import('@/logger');
  resetLogger(); initLogger({ level: 'debug', suppressConsole: true });
  const records: any[] = []; const unsubscribe = addSink((entry: any) => records.push(entry));
  restores.push(() => { unsubscribe(); resetLogger(); });
  return records;
}
afterEach(async () => { for (const restore of restores.splice(0).reverse()) restore(); for (const dir of roots.splice(0)) await rm(dir, { recursive: true, force: true }); });

// Command construction: all seven cases exercise the exported production builder.
test('AC-1: shell assignment and Jest template', async () => { const { buildAcceptanceRunCommand: build } = await import('@/acceptance/generator'); expect(build('/pkg/.nax-acceptance.test.ts', undefined, 'KODA_DB_TESTS=1 npx jest -c j.js {{FILE}}')).toBe("KODA_DB_TESTS=1 npx jest -c j.js '/pkg/.nax-acceptance.test.ts'"); });
test('AC-2: quote whitespace in substituted file', async () => { const { buildAcceptanceRunCommand: build } = await import('@/acceptance/generator'); expect(build('/pkg with spaces/.nax-acceptance.test.ts', undefined, 'bun test {{FILE}}')).toBe("bun test '/pkg with spaces/.nax-acceptance.test.ts'"); });
test('AC-3: escape apostrophe in substituted file', async () => { const { buildAcceptanceRunCommand: build } = await import('@/acceptance/generator'); expect(build("/p/it's/.nax-acceptance.test.ts", undefined, 'bun test {{file}}')).toBe("bun test '/p/it'\\''s/.nax-acceptance.test.ts'"); });
test('AC-4: preserve shell control operator', async () => { const { buildAcceptanceRunCommand: build } = await import('@/acceptance/generator'); const cmd = build('/pkg/a.test.ts', undefined, 'cd sub && bun test {{files}}'); expect(cmd).toBe("cd sub && bun test '/pkg/a.test.ts'"); expect(cmd).not.toContain("'&&'"); });
test('AC-5: trim override whitespace', async () => { const { buildAcceptanceRunCommand: build } = await import('@/acceptance/generator'); expect(build('/pkg/a.test.ts', undefined, '  bun test {{FILE}}  ')).toBe("bun test '/pkg/a.test.ts'"); });
test('AC-6: override without placeholder does not append test path', async () => { const { buildAcceptanceRunCommand: build } = await import('@/acceptance/generator'); const cmd = build('/pkg/a.test.ts', undefined, 'bun test'); expect(cmd).toBe('bun test'); expect(cmd).not.toContain('/pkg/a.test.ts'); });
test('AC-7: default command quotes each argument', async () => { const { buildAcceptanceRunCommand: build } = await import('@/acceptance/generator'); expect(build('/project/.nax-acceptance.test.ts')).toBe("'bun' 'test' '/project/.nax-acceptance.test.ts' '--timeout=60000'"); });
test('AC-8: Jest default quotes each argument', async () => { const { buildAcceptanceRunCommand: build } = await import('@/acceptance/generator'); expect(build('/pkg/.nax-acceptance.test.ts', 'jest')).toBe("'npx' 'jest' '/pkg/.nax-acceptance.test.ts'"); });
test('AC-9: production RED runner accepts shell assignment', async () => { const { _acceptanceSetupDeps } = await import('@/pipeline/stages/acceptance-setup'); const dir = await temporary(); expect((await _acceptanceSetupDeps.runTest(path.join(dir, 'probe.test.ts'), dir, 'NAX_ACC_PROBE=1 true')).exitCode).toBe(0); });
test('AC-10: production RED runner propagates shell environment', async () => { const { _acceptanceSetupDeps } = await import('@/pipeline/stages/acceptance-setup'); const dir = await temporary(); const result = await _acceptanceSetupDeps.runTest(path.join(dir, 'probe.test.ts'), dir, 'NAX_ACC_PROBE=abc printenv NAX_ACC_PROBE'); expect(result.output.includes('abc')).toBe(true); });

async function red(exitCode: number, output: string, language = 'TypeScript') {
  const { DEFAULT_CONFIG } = await import('@/config');
  const { runAcceptanceRedGate } = await import('@/pipeline/stages/acceptance-red-gate');
  const records = await capture();
  const entry = { testPath: '/repo/.nax-acceptance.test.ts', packageDir: '/repo', storyId: 'US-001', language, commandOverride: 'FOO=1 bun test {{FILE}}', config: DEFAULT_CONFIG };
  const deps = { runTest: mock(async () => ({ exitCode, output })), callOp: mock(async () => ({ testCode: null })), writeFile: mock(async () => {}), autoCommitIfDirty: mock(async () => {}) };
  const result = await runAcceptanceRedGate({ workdir: '/repo', prd: { feature: 'f' }, runtime: { dryRun: true } } as any, [entry], deps as any);
  return { result, entry, deps, records };
}
test('AC-11: RED gate passes the built shell command to runTest', async () => { const x = await red(0, ''); expect(x.deps.runTest).toHaveBeenCalledTimes(1); expect(x.deps.runTest.mock.calls[0]![2]).toBe("FOO=1 bun test '/repo/.nax-acceptance.test.ts'"); });

async function stage(exitCode: number, output: string) {
  const { acceptanceStage } = await import('@/pipeline/stages/acceptance');
  const { _executorDeps } = await import('@/verification');
  const { DEFAULT_CONFIG } = await import('@/config');
  const { makeDispatchContext } = await import('../../../test/helpers');
  const dir = await temporary(); const testPath = await put(dir, '.nax-acceptance.test.ts', 'test("AC-1: example", () => {})');
  const records = await capture(); const old = _executorDeps.spawn;
  const spawn = mock(() => ({ exited: Promise.resolve(exitCode), stdout: new Blob([output]).stream(), stderr: new Blob([]).stream(), exitCode }));
  _executorDeps.spawn = spawn as any; restores.push(() => { _executorDeps.spawn = old; });
  const story = { id: 'US-001', title: 'story', description: '', acceptanceCriteria: ['AC-1: example'], tags: [], dependencies: [], status: 'passed', passes: true, escalations: [], attempts: 0 };
  const ctx: any = { ...makeDispatchContext(), config: DEFAULT_CONFIG, rootConfig: DEFAULT_CONFIG, prd: { feature: 'hygiene', userStories: [story] }, story, stories: [story], routing: { complexity: 'simple', modelTier: 'fast', testStrategy: 'test-after', reasoning: '' }, workdir: dir, projectDir: dir, featureDir: path.join(dir, '.nax/features/hygiene'), hooks: { hooks: {} }, acceptanceTestPaths: [{ testPath, packageDir: dir, commandOverride: 'FOO=1 bun test {{FILE}}' }] };
  await acceptanceStage.execute(ctx);
  return { ctx, records, spawn, testPath, dir, cmd: `FOO=1 bun test '${testPath}'` };
}
test('AC-12: post-run acceptance executes override through shell', async () => { const x = await stage(0, '1 pass'); expect(x.spawn.mock.calls[0]![0]).toEqual(['/bin/sh', '-c', x.cmd]); });
test('AC-13: hardening executes override in detached shell', async () => {
  const { runHardeningPass, _hardeningDeps } = await import('@/acceptance/hardening');
  const { DEFAULT_CONFIG } = await import('@/config');
  const { makeDispatchContext } = await import('../../../test/helpers');
  const dir = await temporary(); const old = { ..._hardeningDeps }; restores.push(() => Object.assign(_hardeningDeps, old));
  const calls: any[][] = [];
  _hardeningDeps.callOp = (async (_ctx: any, op: any) => op.name.includes('refine') ? [{ original: 'suggested', refined: 'suggested', testable: true, storyId: 'US-001' }] : { testCode: 'test("AC-1: suggested", () => {})' }) as any;
  _hardeningDeps.detectLanguage = async () => 'TypeScript'; _hardeningDeps.writeFile = async () => {};
  _hardeningDeps.spawn = ((...args: any[]) => { calls.push(args); return { pid: 123, exited: Promise.resolve(1), stdout: new Blob([]).stream(), stderr: new Blob([]).stream() }; }) as any;
  const story = { id: 'US-001', title: 'Story', description: '', acceptanceCriteria: [], suggestedCriteria: ['suggested'], tags: [], dependencies: [], status: 'passed', passes: true, escalations: [], attempts: 0 };
  const config = { ...DEFAULT_CONFIG, acceptance: { ...DEFAULT_CONFIG.acceptance, command: 'FOO=1 bun test {{FILE}}' } };
  const ctx: any = { ...makeDispatchContext(), prd: { feature: 'hygiene', userStories: [story] }, prdPath: path.join(dir, 'prd.json'), featureDir: path.join(dir, '.nax/features/hygiene'), workdir: dir, config, agentManager: { getDefault: () => 'test' } };
  await runHardeningPass(ctx);
  expect(calls).toHaveLength(1); expect(calls[0]![0]).toEqual(['/bin/sh', '-c', expect.stringMatching(/^FOO=1 bun test '.+'$/)]); expect(calls[0]![1].detached).toBe(true);
});
for (const [n, code, expected] of [[14,127,true],[15,126,true],[16,1,false],[17,0,false]] as const) test(`AC-${n}: classify command exit ${code}`, async () => { const { isCommandNotRunnable } = await import('@/test-runners'); expect(isCommandNotRunnable(code)).toBe(expected); });
test('AC-18: exit 127 never dispatches acceptance repair', async () => { const x = await red(127, '/bin/sh: FOO: command not found'); const { acceptanceRepairOp } = await import('@/operations'); expect(x.deps.callOp).toHaveBeenCalledTimes(0); expect(x.deps.callOp.mock.calls.some((c: any[]) => c.some(a => a === acceptanceRepairOp))).toBe(false); });
test('AC-19: exit 127 runs once and never writes or commits', async () => { const x = await red(127, '/bin/sh: FOO: command not found'); expect(x.deps.runTest).toHaveBeenCalledTimes(1); expect(x.deps.runTest.mock.calls[0]![0]).toBe(x.entry.testPath); expect(x.deps.writeFile).toHaveBeenCalledTimes(0); expect(x.deps.autoCommitIfDirty).toHaveBeenCalledTimes(0); });
test('AC-20: exit 127 emits one attributed setup error with actual command', async () => { const x = await red(127, '/bin/sh: FOO: command not found'); const errors = x.records.filter(r => r.level === 'error' && r.stage === 'acceptance-setup'); expect(errors).toHaveLength(1); expect(errors[0].message).toBe('RED gate: acceptance command could not run — check acceptance.command'); expect(Object.keys(errors[0].data)[0]).toBe('storyId'); expect(errors[0].data.cmd).toBe(x.deps.runTest.mock.calls[0]![2]); expect(errors[0].data.exitCode).toBe(127); });
test('AC-21: exit 127 counts as one RED', async () => { expect((await red(127, '/bin/sh: FOO: command not found')).result).toBe(1); });
test('AC-22: ordinary TypeScript crash remains repairable', async () => { const x = await red(1, 'SyntaxError: Unexpected token'); const { acceptanceRepairOp } = await import('@/operations'); expect(x.deps.callOp).toHaveBeenCalledTimes(1); expect(x.deps.callOp.mock.calls[0]![2]).toBe(acceptanceRepairOp); });
test('AC-23: post-run exit 127 records runner-error finding with built command', async () => { const x = await stage(127, 'sh: FOO: command not found'); expect(x.ctx.acceptanceFailures.findings).toContainEqual(expect.objectContaining({ category: 'test-runner-error', message: `Acceptance command could not run (exit 127): ${x.cmd}` })); });
test('AC-24: post-run exit 127 logs actionable attributed error instead of generic crash', async () => { const x = await stage(127, 'sh: FOO: command not found'); const errors = x.records.filter(r => r.level === 'error' && r.stage === 'acceptance'); const r = errors.find(r => r.message === 'Acceptance command could not run — check acceptance.command'); expect(r).toBeDefined(); expect(Object.keys(r.data)[0]).toBe('storyId'); expect(r.data).toMatchObject({ exitCode: 127, cmd: x.cmd, packageDir: x.dir }); expect(errors.filter(r => r.message === 'Tests errored with no AC failures parsed')).toHaveLength(0); });
test('AC-25: post-run exit 127 routes failing package to fix cycle', async () => { const x = await stage(127, 'sh: FOO: command not found'); expect(x.ctx.acceptanceFailures.failedACs).toEqual(['AC-ERROR']); expect(x.ctx.acceptanceFailures.failedPackages).toHaveLength(1); expect(x.ctx.acceptanceFailures.failedPackages[0]).toMatchObject({ packageDir: x.dir, testPath: x.testPath }); });
test('AC-26: exit 1 without tagged AC is a crashed test runner', async () => { const x = await stage(1, 'SyntaxError: Unexpected token'); expect(x.ctx.acceptanceFailures.findings).toContainEqual(expect.objectContaining({ message: 'Test runner crashed before test bodies ran' })); });

// Git-backed tests create isolated repositories; git operations always use their repo as cwd.
test('AC-27: tracked manifest and untracked runs partition separately', async () => { const { detectGeneratedContent, partitionTrackedCandidates } = await import('@/commands/migrate'); const dir = await repo(); await put(dir, M); git(dir, 'add', M); git(dir, 'commit', '-qm', 'manifest'); await put(dir, R); const result = await partitionTrackedCandidates(dir, await detectGeneratedContent(path.join(dir, '.nax'))); expect(result.tracked).toHaveLength(1); expect(path.relative(dir, result.tracked[0].srcPath)).toBe(M); expect(result.migratable).toHaveLength(1); expect(path.relative(dir, result.migratable[0].srcPath)).toBe('.nax/runs'); });
test('AC-28: tracked child marks whole generated directory tracked', async () => { const { partitionTrackedCandidates } = await import('@/commands/migrate'); const dir = await repo(); await put(dir, '.nax/features/f/runs/r.json'); git(dir, 'add', '.nax/features/f/runs/r.json'); git(dir, 'commit', '-qm', 'runs'); const c = { name: 'features/f/runs', srcPath: '.nax/features/f/runs' }; const r = await partitionTrackedCandidates(dir, [c]); expect(r.tracked).toHaveLength(1); expect(r.tracked[0]).toBe(c); expect(r.migratable).toHaveLength(0); });
test('AC-29: runs-archive must not falsely mark runs tracked', async () => { const { partitionTrackedCandidates } = await import('@/commands/migrate'); const dir = await repo(); await put(dir, '.nax/runs-archive/x.json'); git(dir, 'add', '.nax/runs-archive/x.json'); git(dir, 'commit', '-qm', 'archive'); const c = { name: 'runs', srcPath: '.nax/runs' }; const r = await partitionTrackedCandidates(dir, [c]); expect(r.migratable).toContain(c); expect(r.tracked).toHaveLength(0); });
test('AC-30: non-git directory preserves candidate identity and order', async () => { const { partitionTrackedCandidates } = await import('@/commands/migrate'); const dir = await temporary(); const candidates = Array.from({ length: 4 }, (_, i) => ({ name: `c${i}`, srcPath: `.nax/c${i}` })); const r = await partitionTrackedCandidates(dir, candidates); expect(r.tracked).toHaveLength(0); expect(r.migratable).toHaveLength(4); r.migratable.forEach((c: any, i: number) => expect(c).toBe(candidates[i])); });
test('AC-31: auto migration moves untracked runs but keeps tracked manifest', async () => { const { autoMigrateGeneratedContent } = await import('@/commands/migrate'); await capture(); const { dir, outputDir } = await mixed(); await autoMigrateGeneratedContent(dir); expect(existsSync(path.join(outputDir, 'runs/r.json'))).toBe(true); expect(existsSync(path.join(dir, R))).toBe(false); expect(existsSync(path.join(dir, M))).toBe(true); });
test('AC-32: auto migration warns once with actionable tracked paths', async () => { const { autoMigrateGeneratedContent } = await import('@/commands/migrate'); const records = await capture(); const { dir } = await mixed(); await autoMigrateGeneratedContent(dir); const warnings = records.filter(r => r.level === 'warn' && r.message === 'Skipping git-tracked generated content under .nax/ — untrack it with git rm -r --cached'); expect(warnings).toHaveLength(1); expect(warnings[0].data).toMatchObject({ storyId: '_setup', count: 1 }); expect(Array.isArray(warnings[0].data.paths)).toBe(true); expect(warnings[0].data.paths[0]).toBe(M); expect(warnings[0].data.fix).toBe(`git rm -r --cached ${M}`); });
test('AC-33: auto migration is idempotent with tracked leftovers', async () => { const { autoMigrateGeneratedContent } = await import('@/commands/migrate'); const records = await capture(); const { dir } = await mixed(); await autoMigrateGeneratedContent(dir); records.length = 0; await autoMigrateGeneratedContent(dir); expect(records.filter(r => r.level === 'warn' && r.message === 'Auto-migration failed — continuing without migration')).toHaveLength(0); expect(existsSync(path.join(dir, M))).toBe(true); });
test('AC-34: all tracked candidates cause neither migration announcement nor deletion', async () => { const { autoMigrateGeneratedContent, detectGeneratedContent } = await import('@/commands/migrate'); const records = await capture(); const dir = await repo(); await put(dir, '.nax/config.json', JSON.stringify({ outputDir: path.join(dir, 'out') })); await put(dir, M); await put(dir, R); const candidates = await detectGeneratedContent(path.join(dir, '.nax')); expect(candidates).toHaveLength(2); git(dir, 'add', M, R); git(dir, 'commit', '-qm', 'generated'); await autoMigrateGeneratedContent(dir); expect(records.some(r => r.level === 'info' && r.message === 'Found generated content under .nax/ — migrating to output dir')).toBe(false); expect(git(dir, 'status', '--porcelain').split('\n').filter(s => /^\s*D/.test(s))).toHaveLength(0); });
test('AC-35: warn count includes all seven but paths preview is capped at five', async () => { const { autoMigrateGeneratedContent, detectGeneratedContent } = await import('@/commands/migrate'); const records = await capture(); const dir = await repo(); await put(dir, '.nax/config.json', JSON.stringify({ outputDir: path.join(dir, 'out') })); const names = [R, '.nax/metrics.json', '.nax/cost/c.json', '.nax/prompt-audit/a.json', '.nax/review-audit/a.json', '.nax/cycle-shadow/a.json', '.nax/curator/a.json']; for (const n of names) await put(dir, n); expect(await detectGeneratedContent(path.join(dir, '.nax'))).toHaveLength(7); git(dir, 'add', ...names); git(dir, 'commit', '-qm', 'all'); await autoMigrateGeneratedContent(dir); const w = records.find(r => r.level === 'warn' && r.message === 'Skipping git-tracked generated content under .nax/ — untrack it with git rm -r --cached'); expect(w).toBeDefined(); expect(w.data.count).toBe(7); expect(Array.isArray(w.data.paths)).toBe(true); expect(w.data.paths).toHaveLength(5); });
test('AC-36: missing config yields one nonfatal auto-migration warning', async () => { const { autoMigrateGeneratedContent } = await import('@/commands/migrate'); const records = await capture(); const dir = await repo(); await put(dir, R); await autoMigrateGeneratedContent(dir); expect(records.filter(r => r.level === 'warn' && r.message === 'Auto-migration failed — continuing without migration')).toHaveLength(1); });
test('AC-37: explicit migration leaves committed candidates intact', async () => { const { migrateCommand } = await import('@/commands/migrate'); await capture(); const { dir, outputDir } = await mixed(); await migrateCommand({ workdir: dir }); expect(existsSync(path.join(outputDir, 'runs/r.json'))).toBe(true); expect(existsSync(path.join(dir, R))).toBe(false); expect(existsSync(path.join(dir, M))).toBe(true); expect(git(dir, 'diff', '--name-only', '--diff-filter=D')).toBe(''); });
test('AC-38: dry-run reports skip for tracked and move for untracked without moving', async () => { const { migrateCommand } = await import('@/commands/migrate'); const records = await capture(); const { dir, outputDir } = await mixed(); await migrateCommand({ workdir: dir, dryRun: true }); const lines = records.filter(r => r.level === 'info').map(r => r.message); expect(lines.filter(s => s.includes(`[dry-run] Skip (git-tracked): ${M}`))).toHaveLength(1); expect(lines.some(s => s.includes(`[dry-run] Skip (git-tracked): ${R}`))).toBe(false); const moves = lines.filter(s => s.includes('[dry-run] Would move')); expect(moves).toHaveLength(1); expect(moves[0]).toContain('.nax/runs'); expect(moves[0]).not.toContain(M); expect(existsSync(path.join(dir, M))).toBe(true); expect(existsSync(path.join(dir, R))).toBe(true); expect(existsSync(path.join(outputDir, 'runs/r.json'))).toBe(false); });
test('AC-39: partition performs a single batched git ls-files', async () => { const { partitionTrackedCandidates, _gitDeps } = await import('@/commands/migrate'); const dir = await repo(); const original = _gitDeps.spawn; const calls: any[][] = []; _gitDeps.spawn = ((...args: any[]) => { calls.push(args); return original(...args); }) as any; restores.push(() => { _gitDeps.spawn = original; }); await partitionTrackedCandidates(dir, [R, M, '.nax/metrics.json'].map(srcPath => ({ name: path.basename(srcPath), srcPath }))); expect(calls).toHaveLength(1); expect(calls[0]!.some(a => Array.isArray(a) && a.includes('ls-files'))).toBe(true); });
test('AC-40: setup invokes auto migration exactly once before subsequent setup rejection', async () => { const { setupRun, _runSetupDeps } = await import('@/execution/lifecycle/run-setup'); const { DEFAULT_CONFIG } = await import('@/config'); const dir = await temporary(); const prdPath = path.join(dir, 'prd.json'); await writeFile(prdPath, JSON.stringify({ project: 'hygiene', feature: 'hygiene', branchName: 'main', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), userStories: [{ id: 'US-001', title: 'story', description: '', acceptanceCriteria: [], tags: [], dependencies: [], status: 'pending', passes: false, escalations: [], attempts: 0 }] })); const old = { ..._runSetupDeps }; restores.push(() => Object.assign(_runSetupDeps, old)); const auto = mock(async () => {}); _runSetupDeps.autoMigrateGeneratedContent = auto; _runSetupDeps.acquireLock = (async () => { throw new Error('later setup failure'); }) as any; await expect(setupRun({ workdir: dir, config: DEFAULT_CONFIG, hooks: { hooks: {} } as any, feature: 'hygiene', dryRun: true, statusFile: path.join(dir, 'status.json'), runId: 'test', startedAt: new Date().toISOString(), startTime: Date.now(), skipPrecheck: true, headless: true, formatterMode: 'quiet', getTotalCost: () => 0, getIterations: () => 0, getStoriesCompleted: () => 0, getTotalStories: () => 0, prdPath } as any)).rejects.toThrow(); expect(auto).toHaveBeenCalledTimes(1); expect(auto.mock.calls[0]![0]).toBe(dir); });

async function cycle(throwOn: number, costs: number[]) {
  const { runFixCycle } = await import('@/findings/cycle');
  const { makeCycle, makeStrategy, makeCtx, makeCallOpMock, lintA } = await import('../../../test/unit/findings/_cycle-fixtures');
  const records: any[] = []; let dispatch = 0; let validations = 0;
  const logger: any = { error: (stage: string, message: string, data: any) => records.push({ stage, message, data }), info: () => {}, warn: () => {}, debug: () => {} };
  const strategy = makeStrategy({ name: 'lint-fix', maxAttempts: costs.length + 1, extractApplied: () => ({ summary: 'fixed', costUsd: costs[dispatch++ ] }) });
  const c = makeCycle([lintA], [strategy], async () => { if (++validations >= throwOn) throw new Error('validator broke'); return [lintA]; });
  const result = await runFixCycle(c, makeCtx(), 'hygiene', { callOp: makeCallOpMock({}), logger });
  return { result, records };
}
test('AC-41: validator error retains first dispatch spend', async () => { const { result } = await cycle(1, [0.5]); expect(result.exitReason).toBe('validator-error'); expect(Math.abs(result.costUsd - 0.5)).toBeLessThanOrEqual(1e-5); });
test('AC-42: failed first validation records no completed iterations', async () => { const { result } = await cycle(1, [0.5]); expect(result.iterations).toEqual([]); expect(result.iterations).toHaveLength(0); });
test('AC-43: second validator error retains cumulative dispatch spend', async () => { const { result } = await cycle(2, [0.2, 0.5]); expect(result.exitReason).toBe('validator-error'); expect(Math.abs(result.costUsd - 0.7)).toBeLessThanOrEqual(1e-5); });
test('AC-44: validator error logs iteration spend and strategy', async () => { const { records } = await cycle(1, [0.5]); const r = records.find(r => r.stage === 'findings.cycle' && r.message === 'cycle exited — validator error'); expect(r).toBeDefined(); expect(r.data.strategiesRun).toEqual(['lint-fix']); expect(r.data.iterationCostUsd).toBe(0.5); });