/**
 * @nathapp/nax-agent public entry (S1 spec section 4.4, S2 spec section 5.3).
 *
 * Every export is named: nothing reaches this entry through `export *`. No "_"
 * name belongs here; test seams and reset hooks live on ./internal. The built
 * surface of both entries is pinned by api/nax-agent.api.txt (`bun run check:api`).
 *
 * Generated once by S2-7 from the previous `export *` barrels; maintained by hand.
 */

export {
  appendCommandSafetyRow,
  type BuildCommandShadowOptions,
  buildCommandShadow,
  buildRequest,
  type Classify,
  COMMAND_SAFETY_DIR,
  type CommandGuard,
  type CommandSafetyRow,
  type CommandShadow,
  type CommandShadowOptions,
  createCommandGuard,
  createCommandShadow,
  createSystemOneClient,
  detectTmpWrite,
  type ExecRun,
  type FinalOutcome,
  type GuardDecision,
  type GuardInput,
  HARM_OPTIONS,
  HARM_QUESTION_ID,
  type HarmOption,
  isTempOnly,
  type LedgerOutcome,
  type MechanicalVerdict,
  type ModelAnswers,
  type ModelResult,
  type Observation,
  openShadowTap,
  parseAnswer,
  QUESTION_IDS,
  QUESTION_SET_VERSION,
  type QuestionId,
  RULE_SET_VERSION,
  type RuleContext,
  type RuleResult,
  type ShadowCall,
  type ShadowTap,
  SYSTEMONE_MODEL_LABEL,
  type SystemOneClientOptions,
  type SystemOneQuestion,
  type SystemOneRequest,
  scoreGuard,
  scoreRules,
  shadowCacheKey,
  toMechanical,
} from "#src/command-safety/index";
export {
  addTokenUsage,
  estimateCostUsd,
  inputClassTokens,
  type Pricing,
  type PricingRates,
  type PricingTier,
  priceCall,
  type TokenUsage,
} from "#src/cost/core/index";
export {
  type ModelSpec,
  parseModelSpec,
} from "#src/cost/model-spec";
export type { AgentLogger, CredentialAuthConfig, CredentialsConfig } from "#src/infra/index";
export { configureCredentials, setAgentLogger } from "#src/infra/index";
export type { CredentialSource } from "#src/native/credentials/session-source";
export {
  AuthCancelledError,
  type AuthEvent,
  type AuthInteraction,
  type AuthLink,
  type AuthMethod,
  type AuthOption,
  type AuthPrompt,
  type AuthResult,
  ambientShadows,
  anyAmbientCredential,
  authImportOutcomeLabel,
  createFileTranscriptStore,
  createMemoryTranscriptStore,
  credentialFilePath,
  DEFAULT_PI_AUTH_PATH,
  type ImportOutcome,
  importPiCredentials,
  listStoredProviders,
  MAX_RETAINED_TRANSCRIPTS,
  type MemoryTranscriptStore,
  NATIVE_AGENT,
  type NativeCatalogOverrides,
  type NativeCompleteContext,
  type NativeCompleteOptions,
  type NativeCompleteResult,
  NativeSessionAdapter,
  NativeSessionUnsupportedError,
  type NativeTierConfig,
  nativeComplete,
  nativeTierProviders,
  naxCredentialStore,
  newSessionKey,
  providersWithoutCredentials,
  pruneRetainedTranscripts,
  type ResolveResult,
  type ResolveStatus,
  removeStoredProvider,
  resolveNativeId,
  runLogin,
  type StoredEntry,
  servedAuth,
  type TranscriptDoc,
  type TranscriptStore,
  type TurnMarker,
} from "#src/native/index";
export type { NativeSessionAdapterOptions } from "#src/native/session-adapter";
export {
  type ApprovalAuditRow,
  type ApprovalEntry,
  type ApprovalsFile,
  type ApprovalsFileRead,
  type ApprovalsFileState,
  type ApprovalsTaint,
  ASK_CANCELLED_REASON,
  ASK_DENIED_REASON,
  ASK_NO_CHANNEL_REASON,
  ASK_TIMEOUT_REASON,
  ASK_UNAVAILABLE_REASON,
  ASK_UNSHOWABLE_REASON,
  type AskControl,
  type AskDecidedBy,
  type AskDecision,
  type AskLink,
  type AskLinkOutcome,
  type AskRequest,
  type AskResolver,
  type AskVerdict,
  appendApproval,
  appendApprovalAudit,
  approvalId,
  approvalsPath,
  type BashLexResult,
  type BashRedirect,
  type BashSegment,
  type BashSegmentSeparator,
  type BashToken,
  type ClearTaintOutcome,
  chainAskLinks,
  clearApprovalsTaint,
  createApprovalsLink,
  findApproval,
  findSecretSpans,
  headlessAskResolver,
  isForgeCapable,
  lexBashCommand,
  type MaskResult,
  maskForPrompt,
  type PrepareApprovalsStoreOptions,
  parseRuleList,
  parseToolExpression,
  prepareApprovalsStore,
  type RemovalDecision,
  type RemovalResult,
  type ResolvedPermissions,
  readApprovals,
  readApprovalsFile,
  readApprovalsFileDetailed,
  redactForRow,
  redactRowStrings,
  removeApprovals,
  type SecretSpan,
  taintApprovals,
  writeApprovalsFile,
} from "#src/permissions/index";
export {
  type AgentGlobOptions,
  type AgentRuntime,
  type AgentSpawnOptions,
  type AgentSpawnResult,
  type AgentSpawnStdin,
  getAgentRuntime,
  nodeRuntime,
  setAgentRuntime,
} from "#src/runtime/index";
export {
  buildSandboxPolicy,
  type CommandLauncher,
  type CommandLauncherOptions,
  createCommandLauncher,
  createSrtBackend,
  DISABLED_SANDBOX_STATE,
  defaultTempRoots,
  denialHintLine,
  type GitLayout,
  type LaunchRequest,
  type LaunchResult,
  type LaunchSpec,
  LIKELY_SANDBOX_DENIAL,
  listCredentialFiles,
  listGitGuardFiles,
  listNaxEntries,
  type ProbeResult,
  probeSandbox,
  probeSandboxOnce,
  quoteArgvForShell,
  rawBashRefusalReason,
  resetSandboxBackend,
  resolveGitLayout,
  runTempRoots,
  runTmpRoot,
  type SandboxBackend,
  type SandboxBackendName,
  type SandboxNetworkPolicy,
  type SandboxPolicy,
  type SandboxPolicyInput,
  type SandboxRecord,
  type SandboxState,
  type SandboxWrapRequest,
  sandboxBackendFor,
  sandboxSentence,
  sessionTmpDir,
  sessionTmpDirUnder,
  strayCommonDirTripwire,
  unsandboxedSentence,
  warnSandboxUnavailableOnce,
} from "#src/sandbox/index";
export type { AdapterFailure } from "#src/session/adapter-failure";
export type {
  AgentAwaitingHumanEvent,
  AgentCallEndedEvent,
  AgentCallStartedEvent,
  AgentMessageUpdateEvent,
  AgentProcessUpdateEvent,
  AgentStreamEvent,
  AgentStreamEventBase,
  AgentThinkingUpdateEvent,
  AgentToolCallUpdateEvent,
  AgentUsageUpdateEvent,
} from "#src/session/agent-stream-events";
export {
  type AdapterInteraction,
  type AdapterInteractionResponse,
  type InteractionHandler,
  NO_OP_INTERACTION_HANDLER,
} from "#src/session/interaction-handler";
export type { ProtocolIds } from "#src/session/protocol-types";
export {
  type AgentSessionAdapter,
  type AuthStamp,
  type InteractionExchange,
  type InvalidToolCallDetail,
  type OpenSessionOpts,
  type SendTurnOpts,
  type SessionHandle,
  type SessionModel,
  SessionTurnError,
  type TrackedSpawnDeadlineOptions,
  type TurnResult,
} from "#src/session/session-types";
export type {
  JSONSchema,
  ToolDescriptor,
} from "#src/session/tool-descriptor";
export {
  createTurnDeadline,
  type TurnDeadline,
} from "#src/session/turn-deadline";
export {
  adaptProviderTool,
  advertisedSchemaBytes,
  applyModelTruncationPolicy,
  BASH_TIMEOUT_MS,
  BASH_TOOL_NAME,
  buildCommitArgvs,
  buildGitArgv,
  buildGrepArgv,
  type CodingTool,
  type CodingToolName,
  type CodingToolOutcome,
  type CodingToolRuntime,
  classifyExec,
  compileToolPolicy,
  createBashTool,
  createCodingToolRuntime,
  createNoOpToolAuditSink,
  createRunCommandTool,
  createToolAuditSink,
  cutBufferToByteCap,
  DEFAULT_BASH_SHELL,
  DEFAULT_LOG_FORMAT,
  DEFAULT_LOG_MAX_COUNT,
  DEFAULT_TOOL_MAX_BYTES,
  DEFAULT_TOOL_MAX_FILE_BYTES,
  type DeclaredCommandRequest,
  type DeclaredCommandResult,
  type DeclaredCommandRunner,
  deleteTool,
  EXEC_TOOL_NAME,
  type ExecTarget,
  editTool,
  expandMcpRuleGrants,
  expandProviderGrants,
  flushOpenToolAuditSinks,
  GIT_ESCAPE_FLAGS,
  GIT_READ_VERBS,
  getCodingTool,
  gitCommitTool,
  gitExcludePathspecsOf,
  gitIgnorePatternsOf,
  gitTool,
  globTool,
  grepTool,
  isKnownManager,
  listCodingTools,
  MAX_PROVIDER_DESCRIPTION_BYTES,
  MAX_PROVIDER_SCHEMA_BYTES,
  MCP_RULE_TOOL,
  MODEL_MAX_BYTES,
  MODEL_MAX_LINE_CHARS,
  MODEL_MAX_LINES,
  type ModelTruncationOptions,
  mcpRuleAdmits,
  type NormalizeInput,
  type NormalizeResult,
  namespacedToolName,
  narrowGrants,
  normalizeExec,
  normalizeManagerBinary,
  type PolicyVerdict,
  PROVIDER_ID_RE,
  type ProtectedPathsPolicy,
  type ProviderGrantEntry,
  type ProviderKind,
  type ProviderTool,
  partitionMcpRules,
  partitionNaxOwnedPaths,
  providerAttachesTo,
  READ_CEILING,
  RESERVED_TOOL_NAMES,
  type ReadFileSliceOptions,
  type ReadFileSliceResult,
  type RegisteredSink,
  type ResolvedProviderTools,
  readFileSlice,
  readTool,
  registerBuiltinCodingTools,
  registerBuiltinTool,
  registerCodingTool,
  registerToolAuditSink,
  requestCapabilityTool,
  resolveProviderTools,
  resolveWithin,
  SCRATCHPAD_DIR,
  SPILL_DIR,
  type SpillRequest,
  sanitizeProviderTools,
  scratchpadListTool,
  scratchpadReadTool,
  scratchpadWriteTool,
  spillRelativePath,
  substituteCommand,
  substituteCommandSpec,
  type ToolAuditSink,
  type ToolCallContext,
  type ToolCallRecord,
  type ToolGrant,
  type ToolPatternNarrowing,
  type ToolPolicy,
  type ToolPolicyOptions,
  type ToolProvider,
  type ToolResult,
  type ToolRunContext,
  type ToolScope,
  type TruncateForModelOptions,
  type TruncationDirection,
  type TruncationResult,
  truncateForModel,
  truncationDirectionFor,
  unregisterToolAuditSink,
  validateProviderId,
  writeSpill,
  writeTool,
} from "#src/tools/index";
export {
  EMPTY_OWNED_PATHS_POLICY,
  type OwnedBashCandidate,
  type OwnedPathsPolicy,
} from "#src/tools/owned-paths";
