/**
 * Marker for bailWhen predicates generated by nax wrappers (e.g.
 * `withIncreasingFailuresBail`). Outer wrappers (e.g. `withNoProgressBail`)
 * use this to distinguish user-supplied bail predicates from wrapper-generated
 * ones — the no-progress wrapper must outrank count-increase (US-002 AC15)
 * while still respecting user-supplied bail predicates (US-002 AC8).
 */

const NAX_BAIL_WRAPPER = "__naxBailWrapper";

export function markNaxBailWrapper<T extends (...args: never[]) => string | null>(predicate: T): T {
  Object.assign(predicate as object, { [NAX_BAIL_WRAPPER]: true });
  return predicate;
}

export function isNaxBailWrapper<T extends (...args: never[]) => string | null>(predicate: T | undefined): boolean {
  if (!predicate) return false;
  return (predicate as unknown as Record<string, unknown>)[NAX_BAIL_WRAPPER] === true;
}
