import { expect, test } from "bun:test";
import { buildNativeStreamEvent } from "@/agents/native/session/turn-events";
import { createHumanAskLink } from "@/interaction/ask-link";
import { chainAskLinks } from "@/permissions/ask-chain";

const request = { tool:"Bash", stage:"implementer", rule:"Bash", summary:"x", command:"echo x", root:"/repo" } as any;
const tick = () => new Promise<void>((r) => queueMicrotask(r));

/* Remaining acceptance cases live beside the main satellite so Bun discovers
 * them with the feature directory.  They use recording collaborators, never
 * source inspection. */
test("AC-31: interaction handler forwards signal and onWaiting to callTool", async () => {
  const { buildRunInteractionHandler } = await import("@/agents/run-interaction-handler"); const signal=new AbortController().signal, waiting=()=>{}; let context:any;
  const handler:any=buildRunInteractionHandler({codingToolRuntime:{callTool:async (_:any,__:any,c:any)=>{context=c;return {kind:"ok",content:"ok"}}},signal,onWaiting:waiting} as any);
  await handler.onInteraction({kind:"coding-tool",name:"T",input:{}}); expect(context.signal).toBe(signal); expect(context.onWaiting).toBe(waiting);
});
test("AC-32: runtime passes ToolCallContext.signal to ToolRunContext", async () => { const { createCodingToolRuntime }=await import("@/tools/runtime") as any; const s=new AbortController().signal; let seen:any; const runtime=createCodingToolRuntime({tools:[{name:"T",run:async (_:any,c:any)=>{seen=c.signal;return {content:"ok"}}}],policy:{}}); await runtime.callTool("T",{}, {signal:s}); expect(seen).toBe(s); });
test("AC-33: cancelled ask denial has the cancellation reason", async () => { const { createCodingToolRuntime }=await import("@/tools/runtime") as any; const runtime=createCodingToolRuntime({askResolver:{resolve:async()=>({decision:"deny",decidedBy:"cancelled"})},policy:{}}); const r=await runtime.callTool("T",{}); expect(r.denied).toBe(true); expect(r.reason).toContain("Not run: the turn was cancelled before anyone answered."); });
test("AC-34: chainAskLinks forwards the same ask control object", async () => { let seen:any; const control={signal:new AbortController().signal,onWaiting:()=>{}}; const resolver:any=chainAskLinks([{name:"x",resolve:async (_:any,c:any)=>{seen=c;return {decision:"deny",decidedBy:"cancelled"}}} as any] as any); await resolver.resolve(request,control); expect(seen).toBe(control); });
test("AC-35: dispatch forwards control but omits it from audit request", async () => { const { createDispatchAskResolver }=await import("@/permissions") as any; let human:any,audit:any; const c={signal:new AbortController().signal,onWaiting:()=>{}}; const resolver=createDispatchAskResolver({human:{resolve:async (_:any,x:any)=>{human=x;return {decision:"deny",decidedBy:"cancelled"}}},audit:(x:any)=>audit=x}); await resolver.resolve(request,c); expect(human).toBe(c); expect(Object.keys(audit.request ?? audit)).not.toContain("signal"); expect(Object.keys(audit.request ?? audit)).not.toContain("onWaiting"); });
test("AC-36: aborting a pending human waiter resolves cancelled", async () => { let release:any; const chain:any={prompt:()=>new Promise(r=>release=r),cancel:async()=>{}}; const c=new AbortController(), link:any=createHumanAskLink({chain,timeoutMs:10_000}); const p=link.resolve(request,{signal:c.signal}); let settled=false;p.then(()=>settled=true);await tick();expect(settled).toBe(false);c.abort();expect(await p).toMatchObject({decision:"deny",decidedBy:"cancelled"}); release?.({action:"allow"}); });
test("AC-37: sole aborted waiter cancels prompt once", async () => { let cancel=0;const chain:any={prompt:async()=>new Promise(()=>{}),cancel:async(id:string)=>{cancel++;expect(id).toBe("p-1")}};const c=new AbortController();const link:any=createHumanAskLink({chain,timeoutMs:10000});const p=link.resolve({...request,id:"p-1"},{signal:c.signal});c.abort();await p;expect(cancel).toBe(1); });
test("AC-38: first of two joined waiters cancels independently", async () => { let allow:any;const chain:any={prompt:()=>new Promise(r=>allow=r),cancel:async()=>{}};const a=new AbortController(),b=new AbortController(),link:any=createHumanAskLink({chain,timeoutMs:10000});const order:string[]=[];const p1=link.resolve(request,{signal:a.signal}).then((x:any)=>{order.push("one");return x});const p2=link.resolve(request,{signal:b.signal}).then((x:any)=>{order.push("two");return x});a.abort();expect(await p1).toMatchObject({decidedBy:"cancelled"});allow({action:"allow"});expect(await p2).toMatchObject({decision:"allow"});expect(order).toEqual(["one","two"]); });
test("AC-39: one of two waiter aborts does not cancel shared prompt", async () => { let cancel=0;const chain:any={prompt:()=>new Promise(()=>{}),cancel:async()=>{cancel++}};const a=new AbortController(),b=new AbortController(),link:any=createHumanAskLink({chain,timeoutMs:10000});const p1=link.resolve(request,{signal:a.signal});void link.resolve(request,{signal:b.signal});a.abort();await p1;expect(cancel).toBe(0); });
test("AC-40: both shared waiters abort cancel once", async () => { let cancel=0;const chain:any={prompt:()=>new Promise(()=>{}),cancel:async()=>{cancel++}};const a=new AbortController(),b=new AbortController(),link:any=createHumanAskLink({chain,timeoutMs:10000});const p1=link.resolve(request,{signal:a.signal}),p2=link.resolve(request,{signal:b.signal});a.abort();await p1;b.abort();await p2;expect(cancel).toBe(1); });
test("AC-41: queued aborted request never prompts", async () => { let prompts=0,release:any;const chain:any={prompt:()=>{prompts++;return new Promise(r=>release=r)},cancel:async()=>{}};const first=new AbortController(),queued=new AbortController(),link:any=createHumanAskLink({chain,timeoutMs:10000});const p1=link.resolve({...request,command:"one"},{signal:first.signal});const p2=link.resolve({...request,command:"two"},{signal:queued.signal});queued.abort();release({action:"allow"});await p1;expect(await p2).toMatchObject({decidedBy:"cancelled"});expect(prompts).toBe(1); });
test("AC-42: already aborted request does not join queue or prompt", async () => { let prompts=0;const c=new AbortController();c.abort();const link:any=createHumanAskLink({chain:{prompt:async()=>{prompts++;return {action:"allow"}},cancel:async()=>{}},timeoutMs:10000});expect(await link.resolve(request,{signal:c.signal})).toMatchObject({decision:"deny",decidedBy:"cancelled"});expect(prompts).toBe(0); });
test("AC-43: post-allow abort prevents tool execution", async () => { const { createCodingToolRuntime }=await import("@/tools/runtime") as any;const c=new AbortController();let runs=0;const r=createCodingToolRuntime({askResolver:{resolve:async()=>{c.abort();return {decision:"allow",decidedBy:"human"}}},tools:[{name:"T",run:async()=>{runs++;return {content:"bad"}}}],policy:{}});const out=await r.callTool("T",{}, {signal:c.signal});expect(runs).toBe(0);expect(out.reason).toContain("Not run: the turn was cancelled before anyone answered."); });
test("AC-44: post-allow cancellation audit outcome is denied:ask", async () => { const { createCodingToolRuntime }=await import("@/tools/runtime") as any;const c=new AbortController(),rows:any[]=[];const r=createCodingToolRuntime({askResolver:{resolve:async()=>{c.abort();return {decision:"allow",decidedBy:"human"}}},auditSink:{append:(x:any)=>rows.push(x)},policy:{}});await r.callTool("T",{}, {signal:c.signal});expect(rows).toHaveLength(1);expect(rows[0].outcome).toBe("denied:ask"); });
test("AC-45: cancelled dispatch writes one cancelled approval audit row", async () => { const { createDispatchAskResolver }=await import("@/permissions") as any;const rows:any[]=[];const r=createDispatchAskResolver({human:{resolve:async()=>({decision:"deny",decidedBy:"cancelled"})},audit:(x:any)=>rows.push(x)});await r.resolve(request,{signal:new AbortController().signal});expect(rows.filter(x=>x.decidedBy!=="cancelled")).toHaveLength(0);expect(rows[0].decidedBy).toBe("cancelled"); });
test("AC-46: onWaiting activity is awaiting_human", async () => { const { runToolBatch }=await import("@/agents/native/session/turn-tool-batch") as any;let activity:any;let waiting:any;await runToolBatch({toolCalls:[{id:"a",name:"T",input:{}}],messages:[],tools:[],codingToolNames:new Set(["T"]),opts:{interactionHandler:{onInteraction:async(x:any)=>{waiting=x.onWaiting;return {answer:"ok"}}},deps:{onActivity:(x:any)=>activity=x},loopEvents:{dispatch:async()=>({kind:"allow"})},invalidCallBudget:{exceeded:false},interactionsSoFar:0,maxInteractions:0,roundTrips:0});waiting();expect(activity.kind).toBe("awaiting_human"); });
test("AC-47: awaiting prompt keepalive uses re-armed timeout cadence", async () => { const { createAskKeepalive }=await import("@/permissions") as any;let n=0,interval=0;const timer:any={setTimeout:(f:any)=>{f();return 1},clearTimeout:()=>{},setInterval:()=>{interval++}};createAskKeepalive({onWaiting:()=>n++,timer}).start();expect(n).toBe(2);expect(interval).toBe(0); });
test("AC-48: keepalive timer is cleared on every settlement", async () => { const { createAskKeepalive }=await import("@/permissions") as any;let f:any,n=0;const k=createAskKeepalive({onWaiting:()=>n++,timer:{setTimeout:(x:any)=>{f=x;return 1},clearTimeout:()=>{f=undefined}}});k.start();k.stop();f?.();expect(n).toBe(1); });
test("AC-49: awaiting_human becomes native awaiting-human stream event", () => { const e:any=buildNativeStreamEvent({callId:"call",runId:"r",agentName:"a",sessionName:"s"},{kind:"awaiting_human"} as any,1);expect(e.kind).toBe("agent.awaiting_human");expect(e.callId).toBe("call"); });
test("AC-50: awaiting_human activity prevents idle watchdog cancellation", async () => { const { createIdleWatchdog }=await import("@/runtime/middleware/idle-watchdog") as any;let n=0;const w=createIdleWatchdog({activityKinds:["message_update"],idleTimeoutMs:1000,cancel:()=>n++});for(let t=0;t<=5000;t+=500)w.activity({kind:"agent.awaiting_human",timestamp:t});expect(n).toBe(0); });
test("AC-51: awaiting_human clears warn grace", async () => { const { createIdleWatchdog }=await import("@/runtime/middleware/idle-watchdog") as any;let n=0;const w=createIdleWatchdog({idleTimeoutMs:1000,cancel:()=>n++});w.warn(0);w.activity({kind:"agent.awaiting_human",timestamp:500});w.tick(1000);expect(n).toBe(0); });
test("AC-52: mixed tool and awaiting activity avoids both watchdog timeouts", async () => { const { createIdleWatchdog }=await import("@/runtime/middleware/idle-watchdog") as any;let n=0;const w=createIdleWatchdog({idleTimeoutMs:1000,toolOnlyTimeoutMs:2000,cancel:()=>n++});for(let t=0;t<=5000;t+=500){w.activity({kind:"agent.tool_call_update",timestamp:t});w.activity({kind:"agent.awaiting_human",timestamp:t});w.tick(t)}expect(n).toBe(0); });
test("AC-53: tool-only activity hits tool-only watchdog at 2000ms", async () => { const { createIdleWatchdog }=await import("@/runtime/middleware/idle-watchdog") as any;let n=0;const w=createIdleWatchdog({idleTimeoutMs:1000,toolOnlyTimeoutMs:2000,cancel:()=>n++});for(let t=0;t<=2000;t+=500){w.activity({kind:"agent.tool_call_update",timestamp:t});w.tick(t)}expect(n).toBe(1); });
test("AC-54: awaiting_human emission does not produce listener threw warnings", async () => { const { createStreamBus }=await import("@/runtime") as any;const warnings:string[]=[];const bus=createStreamBus({logger:{warn:(_:any,m:string)=>warnings.push(m)}});bus.subscribe(()=>{});bus.emit({kind:"agent.awaiting_human",callId:"c"});expect(warnings.filter(x=>x.includes("listener threw"))).toHaveLength(0); });
